IF OBJECT_ID('dbo.IDIOMA_ELIMINAR', 'P') IS NOT NULL DROP PROCEDURE [dbo].[IDIOMA_ELIMINAR]
GO
CREATE PROCEDURE [dbo].[IDIOMA_ELIMINAR]
    @id INT
AS
BEGIN
    SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM IDIOMA WHERE ID = @id AND PREDETERMINADO = 1)
        THROW 50001, 'No se puede eliminar el idioma predeterminado del sistema.', 1;

    IF EXISTS (SELECT 1 FROM USUARIO WHERE IDIOMA_ID = @id)
        THROW 50002, 'No se puede eliminar un idioma que está en uso por algún usuario.', 1;

    BEGIN TRANSACTION;
        DELETE FROM TRADUCCION WHERE IDIOMA_ID = @id;
        DELETE FROM IDIOMA     WHERE ID        = @id;
    COMMIT TRANSACTION;
END
GO

IF OBJECT_ID('dbo.USUARIO_PERFIL_LISTAR_ACTIVOS', 'P') IS NOT NULL DROP PROCEDURE [dbo].[USUARIO_PERFIL_LISTAR_ACTIVOS]
GO
CREATE PROCEDURE [dbo].[USUARIO_PERFIL_LISTAR_ACTIVOS]
AS
    SELECT u.ID AS USUARIO_ID, up.PERFIL_ID
    FROM USUARIO u
    LEFT JOIN USUARIO_PERFIL up ON up.USUARIO_ID = u.ID
    WHERE u.BLOQUEADO = 0
GO
