USE [master]
GO
/****** Object:  Database [BDCAPAS]    Script Date: 04/10/2026 12:15:33 AM ******/
CREATE DATABASE [BDCAPAS]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDCAPAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDCAPAS] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [BDCAPAS] SET ANSI_NULLS OFF
GO
ALTER DATABASE [BDCAPAS] SET ANSI_PADDING OFF
GO
ALTER DATABASE [BDCAPAS] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [BDCAPAS] SET ARITHABORT OFF
GO
ALTER DATABASE [BDCAPAS] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [BDCAPAS] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [BDCAPAS] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [BDCAPAS] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [BDCAPAS] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [BDCAPAS] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [BDCAPAS] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [BDCAPAS] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [BDCAPAS] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [BDCAPAS] SET  DISABLE_BROKER
GO
ALTER DATABASE [BDCAPAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [BDCAPAS] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [BDCAPAS] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [BDCAPAS] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [BDCAPAS] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [BDCAPAS] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [BDCAPAS] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [BDCAPAS] SET RECOVERY SIMPLE
GO
ALTER DATABASE [BDCAPAS] SET  MULTI_USER
GO
ALTER DATABASE [BDCAPAS] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [BDCAPAS] SET DB_CHAINING OFF
GO
ALTER DATABASE [BDCAPAS] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [BDCAPAS] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [BDCAPAS] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [BDCAPAS] SET QUERY_STORE = ON
GO
ALTER DATABASE [BDCAPAS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BDCAPAS]
GO
/****** Object:  Table [dbo].[ALERTA_REVISION]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALERTA_REVISION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPO_ID] [int] NOT NULL,
	[FECHA_GENERACION] [datetime] NOT NULL,
	[ESTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_ALERTA_REVISION] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASISTENCIA_PERSONAL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASISTENCIA_PERSONAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[FECHA] [date] NOT NULL,
	[HORA_INGRESO] [time](7) NOT NULL,
	[HORA_EGRESO] [time](7) NULL,
 CONSTRAINT [PK_ASISTENCIA_PERSONAL] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BITACORA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BITACORA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](50) NULL,
	[ACCION] [varchar](50) NULL,
	[FECHA] [datetime] NULL,
 CONSTRAINT [PK_BITACORA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTROL_IDIOMA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTROL_IDIOMA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CLAVE] [varchar](100) NOT NULL,
	[TEXTO_DEFAULT] [varchar](200) NOT NULL,
 CONSTRAINT [PK_CONTROL_IDIOMA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED
(
	[CLAVE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEMANDA_ESTIMADA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEMANDA_ESTIMADA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FRANJA_ID] [int] NOT NULL,
	[SEMANA] [date] NOT NULL,
	[ROL_REQUERIDO] [varchar](30) NOT NULL,
	[CANTIDAD_PERSONAL_NECESARIO] [int] NOT NULL,
	[ORIGEN_DATO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_DEMANDA_ESTIMADA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIGITO_VERIFICADOR_VERTICAL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIGITO_VERIFICADOR_VERTICAL](
	[TABLA] [varchar](50) NOT NULL,
	[COLUMNA] [varchar](50) NOT NULL,
	[DVV] [int] NOT NULL,
 CONSTRAINT [PK_DVV] PRIMARY KEY CLUSTERED
(
	[TABLA] ASC,
	[COLUMNA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISPONIBILIDAD]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISPONIBILIDAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[SEMANA] [date] NOT NULL,
 CONSTRAINT [PK_DISPONIBILIDAD] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISPONIBILIDAD_FRANJA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISPONIBILIDAD_FRANJA](
	[DISPONIBILIDAD_ID] [int] NOT NULL,
	[FRANJA_ID] [int] NOT NULL,
 CONSTRAINT [PK_DISPONIBILIDAD_FRANJA] PRIMARY KEY CLUSTERED
(
	[DISPONIBILIDAD_ID] ASC,
	[FRANJA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIPO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIPO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[USO_ACUMULADO] [int] NOT NULL,
	[NIVEL_USO_CRITICO] [int] NULL,
	[ESTADO] [varchar](20) NOT NULL,
	[TECNICO_HABITUAL_ID] [int] NULL,
 CONSTRAINT [PK_EQUIPO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIPO_USO_LOG]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIPO_USO_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPO_ID] [int] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[INCREMENTO] [int] NOT NULL,
 CONSTRAINT [PK_EQUIPO_USO_LOG] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EVALUACION_COBERTURA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVALUACION_COBERTURA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FRANJA_ID] [int] NOT NULL,
	[SEMANA] [date] NOT NULL,
	[RESULTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_EVALUACION_COBERTURA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FRANJA_HORARIA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FRANJA_HORARIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DIA] [varchar](15) NOT NULL,
	[HORA_INICIO] [time](7) NOT NULL,
	[HORA_FIN] [time](7) NOT NULL,
	[ROL_REQUERIDO] [varchar](30) NOT NULL,
 CONSTRAINT [PK_FRANJA_HORARIA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GRILLA_TURNOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GRILLA_TURNOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ADMINISTRADOR_ID] [int] NOT NULL,
	[SEMANA] [date] NOT NULL,
	[ESTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_GRILLA_TURNOS] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORIAL_ASISTENCIA_SOCIOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_ASISTENCIA_SOCIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FRANJA_ID] [int] NOT NULL,
	[FECHA] [date] NOT NULL,
	[CANTIDAD_SOCIOS] [int] NOT NULL,
 CONSTRAINT [PK_HISTORIAL_ASISTENCIA_SOCIOS] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IDIOMA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDIOMA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[HABILITADO] [bit] NOT NULL,
	[PREDETERMINADO] [bit] NOT NULL,
 CONSTRAINT [PK_IDIOMA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INFORME_MANTENIMIENTO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INFORME_MANTENIMIENTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VISITA_ID] [int] NOT NULL,
	[RESULTADO] [varchar](300) NOT NULL,
	[PENDIENTE_REPUESTO] [bit] NOT NULL,
	[FECHA_EMISION] [datetime] NOT NULL,
	[CERRADO] [bit] NOT NULL,
 CONSTRAINT [PK_INFORME_MANTENIMIENTO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NODO_PERMISO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NODO_PERMISO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[TIPO] [varchar](10) NOT NULL,
	[PADRE_ID] [int] NULL,
	[PROTEGIDO] [bit] NOT NULL,
 CONSTRAINT [PK_NODO_PERMISO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICACION]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICACION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GRILLA_ID] [int] NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[MENSAJE] [varchar](300) NOT NULL,
	[FECHA_ENVIO] [datetime] NOT NULL,
	[ESTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_NOTIFICACION] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[PADRE_ID] [int] NULL,
	[PROTEGIDO] [bit] NOT NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROL_PERMISO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL_PERMISO](
	[ROL_ID] [int] NOT NULL,
	[PERMISO_ID] [int] NOT NULL,
 CONSTRAINT [PK_ROL_PERMISO] PRIMARY KEY CLUSTERED
(
	[ROL_ID] ASC,
	[PERMISO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRADUCCION]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRADUCCION](
	[IDIOMA_ID] [int] NOT NULL,
	[CONTROL_ID] [int] NOT NULL,
	[TEXTO] [varchar](200) NOT NULL,
 CONSTRAINT [PK_TRADUCCION] PRIMARY KEY CLUSTERED
(
	[IDIOMA_ID] ASC,
	[CONTROL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TURNO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TURNO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GRILLA_ID] [int] NOT NULL,
	[FRANJA_ID] [int] NOT NULL,
	[USUARIO_ID] [int] NULL,
	[ROL_REQUERIDO] [varchar](30) NOT NULL,
	[ESTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_TURNO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](50) NULL,
	[PASS] [varchar](64) NULL,
	[INTENTOS_FALLIDOS] [int] NOT NULL,
	[BLOQUEADO] [bit] NOT NULL,
	[ROL] [varchar](20) NOT NULL,
	[DVH] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[APELLIDO] [varchar](50) NULL,
	[IDIOMA_ID] [int] NULL,
	[ROL_ID] [int] NULL,
	[TELEFONO] [varchar](30) NULL,
	[EMAIL] [varchar](100) NULL,
	[LIMITE_HORAS_SEMANALES] [int] NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO_HISTORIAL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO_HISTORIAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[USUARIO_LOGIN] [varchar](50) NOT NULL,
	[ROL] [varchar](20) NOT NULL,
	[BLOQUEADO] [bit] NOT NULL,
	[INTENTOS_FALLIDOS] [int] NOT NULL,
	[PERFILES] [varchar](500) NOT NULL,
	[FECHA_CAMBIO] [datetime] NOT NULL,
	[REALIZADO_POR] [varchar](50) NOT NULL,
	[TIPO_CAMBIO] [varchar](25) NOT NULL,
	[VERSION_ORIGEN] [int] NULL,
	[NOMBRE] [varchar](50) NULL,
	[APELLIDO] [varchar](50) NULL,
	[TELEFONO] [varchar](30) NULL,
	[EMAIL] [varchar](100) NULL,
	[ROL_ID] [int] NULL,
 CONSTRAINT [PK_USUARIO_HISTORIAL] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO_PERFIL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO_PERFIL](
	[USUARIO_ID] [int] NOT NULL,
	[PERFIL_ID] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO_PERFIL] PRIMARY KEY CLUSTERED
(
	[USUARIO_ID] ASC,
	[PERFIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VISITA_TECNICA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VISITA_TECNICA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ALERTA_ID] [int] NOT NULL,
	[TECNICO_ID] [int] NOT NULL,
	[FECHA_COORDINADA] [datetime] NOT NULL,
	[ESTADO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_VISITA_TECNICA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIGITO_VERIFICADOR_VERTICAL] ADD  DEFAULT ((0)) FOR [DVV]
GO
ALTER TABLE [dbo].[EQUIPO] ADD  DEFAULT ((0)) FOR [USO_ACUMULADO]
GO
ALTER TABLE [dbo].[EQUIPO] ADD  DEFAULT ('Operativo') FOR [ESTADO]
GO
ALTER TABLE [dbo].[FRANJA_HORARIA] ADD  DEFAULT ('Sala') FOR [ROL_REQUERIDO]
GO
ALTER TABLE [dbo].[IDIOMA] ADD  DEFAULT ((1)) FOR [HABILITADO]
GO
ALTER TABLE [dbo].[IDIOMA] ADD  DEFAULT ((0)) FOR [PREDETERMINADO]
GO
ALTER TABLE [dbo].[INFORME_MANTENIMIENTO] ADD  DEFAULT ((0)) FOR [PENDIENTE_REPUESTO]
GO
ALTER TABLE [dbo].[INFORME_MANTENIMIENTO] ADD  DEFAULT ((0)) FOR [CERRADO]
GO
ALTER TABLE [dbo].[NODO_PERMISO] ADD  DEFAULT ((0)) FOR [PROTEGIDO]
GO
ALTER TABLE [dbo].[ROL] ADD  DEFAULT ((0)) FOR [PROTEGIDO]
GO
ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT ((0)) FOR [INTENTOS_FALLIDOS]
GO
ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT ((0)) FOR [BLOQUEADO]
GO
ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT ('usuario') FOR [ROL]
GO
ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT ((0)) FOR [DVH]
GO
ALTER TABLE [dbo].[USUARIO_HISTORIAL] ADD  DEFAULT (getdate()) FOR [FECHA_CAMBIO]
GO
ALTER TABLE [dbo].[ALERTA_REVISION]  WITH CHECK ADD  CONSTRAINT [FK_ALERTA_EQUIPO] FOREIGN KEY([EQUIPO_ID])
REFERENCES [dbo].[EQUIPO] ([ID])
GO
ALTER TABLE [dbo].[ALERTA_REVISION] CHECK CONSTRAINT [FK_ALERTA_EQUIPO]
GO
ALTER TABLE [dbo].[ASISTENCIA_PERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_ASISTPERS_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[ASISTENCIA_PERSONAL] CHECK CONSTRAINT [FK_ASISTPERS_USUARIO]
GO
ALTER TABLE [dbo].[DEMANDA_ESTIMADA]  WITH CHECK ADD  CONSTRAINT [FK_DEMANDA_FRANJA] FOREIGN KEY([FRANJA_ID])
REFERENCES [dbo].[FRANJA_HORARIA] ([ID])
GO
ALTER TABLE [dbo].[DEMANDA_ESTIMADA] CHECK CONSTRAINT [FK_DEMANDA_FRANJA]
GO
ALTER TABLE [dbo].[DISPONIBILIDAD]  WITH CHECK ADD  CONSTRAINT [FK_DISPONIBILIDAD_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[DISPONIBILIDAD] CHECK CONSTRAINT [FK_DISPONIBILIDAD_USUARIO]
GO
ALTER TABLE [dbo].[DISPONIBILIDAD_FRANJA]  WITH CHECK ADD  CONSTRAINT [FK_DISPFRANJA_DISP] FOREIGN KEY([DISPONIBILIDAD_ID])
REFERENCES [dbo].[DISPONIBILIDAD] ([ID])
GO
ALTER TABLE [dbo].[DISPONIBILIDAD_FRANJA] CHECK CONSTRAINT [FK_DISPFRANJA_DISP]
GO
ALTER TABLE [dbo].[DISPONIBILIDAD_FRANJA]  WITH CHECK ADD  CONSTRAINT [FK_DISPFRANJA_FRANJA] FOREIGN KEY([FRANJA_ID])
REFERENCES [dbo].[FRANJA_HORARIA] ([ID])
GO
ALTER TABLE [dbo].[DISPONIBILIDAD_FRANJA] CHECK CONSTRAINT [FK_DISPFRANJA_FRANJA]
GO
ALTER TABLE [dbo].[EQUIPO]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPO_TECNICO] FOREIGN KEY([TECNICO_HABITUAL_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[EQUIPO] CHECK CONSTRAINT [FK_EQUIPO_TECNICO]
GO
ALTER TABLE [dbo].[EQUIPO_USO_LOG]  WITH CHECK ADD  CONSTRAINT [FK_USOLOG_EQUIPO] FOREIGN KEY([EQUIPO_ID])
REFERENCES [dbo].[EQUIPO] ([ID])
GO
ALTER TABLE [dbo].[EQUIPO_USO_LOG] CHECK CONSTRAINT [FK_USOLOG_EQUIPO]
GO
ALTER TABLE [dbo].[EVALUACION_COBERTURA]  WITH CHECK ADD  CONSTRAINT [FK_EVALCOB_FRANJA] FOREIGN KEY([FRANJA_ID])
REFERENCES [dbo].[FRANJA_HORARIA] ([ID])
GO
ALTER TABLE [dbo].[EVALUACION_COBERTURA] CHECK CONSTRAINT [FK_EVALCOB_FRANJA]
GO
ALTER TABLE [dbo].[GRILLA_TURNOS]  WITH CHECK ADD  CONSTRAINT [FK_GRILLA_ADMIN] FOREIGN KEY([ADMINISTRADOR_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[GRILLA_TURNOS] CHECK CONSTRAINT [FK_GRILLA_ADMIN]
GO
ALTER TABLE [dbo].[HISTORIAL_ASISTENCIA_SOCIOS]  WITH CHECK ADD  CONSTRAINT [FK_HISTASIST_FRANJA] FOREIGN KEY([FRANJA_ID])
REFERENCES [dbo].[FRANJA_HORARIA] ([ID])
GO
ALTER TABLE [dbo].[HISTORIAL_ASISTENCIA_SOCIOS] CHECK CONSTRAINT [FK_HISTASIST_FRANJA]
GO
ALTER TABLE [dbo].[INFORME_MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_INFORME_VISITA] FOREIGN KEY([VISITA_ID])
REFERENCES [dbo].[VISITA_TECNICA] ([ID])
GO
ALTER TABLE [dbo].[INFORME_MANTENIMIENTO] CHECK CONSTRAINT [FK_INFORME_VISITA]
GO
ALTER TABLE [dbo].[NOTIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_GRILLA] FOREIGN KEY([GRILLA_ID])
REFERENCES [dbo].[GRILLA_TURNOS] ([ID])
GO
ALTER TABLE [dbo].[NOTIFICACION] CHECK CONSTRAINT [FK_NOTIF_GRILLA]
GO
ALTER TABLE [dbo].[NOTIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[NOTIFICACION] CHECK CONSTRAINT [FK_NOTIF_USUARIO]
GO
ALTER TABLE [dbo].[ROL]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PADRE] FOREIGN KEY([PADRE_ID])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[ROL] CHECK CONSTRAINT [FK_ROL_PADRE]
GO
ALTER TABLE [dbo].[ROL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_ROLPERM_PERMISO] FOREIGN KEY([PERMISO_ID])
REFERENCES [dbo].[PERMISO] ([ID])
GO
ALTER TABLE [dbo].[ROL_PERMISO] CHECK CONSTRAINT [FK_ROLPERM_PERMISO]
GO
ALTER TABLE [dbo].[ROL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_ROLPERM_ROL] FOREIGN KEY([ROL_ID])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[ROL_PERMISO] CHECK CONSTRAINT [FK_ROLPERM_ROL]
GO
ALTER TABLE [dbo].[TRADUCCION]  WITH CHECK ADD  CONSTRAINT [FK_TRAD_CONTROL] FOREIGN KEY([CONTROL_ID])
REFERENCES [dbo].[CONTROL_IDIOMA] ([ID])
GO
ALTER TABLE [dbo].[TRADUCCION] CHECK CONSTRAINT [FK_TRAD_CONTROL]
GO
ALTER TABLE [dbo].[TRADUCCION]  WITH CHECK ADD  CONSTRAINT [FK_TRAD_IDIOMA] FOREIGN KEY([IDIOMA_ID])
REFERENCES [dbo].[IDIOMA] ([ID])
GO
ALTER TABLE [dbo].[TRADUCCION] CHECK CONSTRAINT [FK_TRAD_IDIOMA]
GO
ALTER TABLE [dbo].[TURNO]  WITH CHECK ADD  CONSTRAINT [FK_TURNO_FRANJA] FOREIGN KEY([FRANJA_ID])
REFERENCES [dbo].[FRANJA_HORARIA] ([ID])
GO
ALTER TABLE [dbo].[TURNO] CHECK CONSTRAINT [FK_TURNO_FRANJA]
GO
ALTER TABLE [dbo].[TURNO]  WITH CHECK ADD  CONSTRAINT [FK_TURNO_GRILLA] FOREIGN KEY([GRILLA_ID])
REFERENCES [dbo].[GRILLA_TURNOS] ([ID])
GO
ALTER TABLE [dbo].[TURNO] CHECK CONSTRAINT [FK_TURNO_GRILLA]
GO
ALTER TABLE [dbo].[TURNO]  WITH CHECK ADD  CONSTRAINT [FK_TURNO_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[TURNO] CHECK CONSTRAINT [FK_TURNO_USUARIO]
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_IDIOMA] FOREIGN KEY([IDIOMA_ID])
REFERENCES [dbo].[IDIOMA] ([ID])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_IDIOMA]
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_ROL] FOREIGN KEY([ROL_ID])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_ROL]
GO
ALTER TABLE [dbo].[USUARIO_PERFIL]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOPERFIL_ROL] FOREIGN KEY([PERFIL_ID])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[USUARIO_PERFIL] CHECK CONSTRAINT [FK_USUARIOPERFIL_ROL]
GO
ALTER TABLE [dbo].[VISITA_TECNICA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_ALERTA] FOREIGN KEY([ALERTA_ID])
REFERENCES [dbo].[ALERTA_REVISION] ([ID])
GO
ALTER TABLE [dbo].[VISITA_TECNICA] CHECK CONSTRAINT [FK_VISITA_ALERTA]
GO
ALTER TABLE [dbo].[VISITA_TECNICA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_TECNICO] FOREIGN KEY([TECNICO_ID])
REFERENCES [dbo].[USUARIO] ([ID])
GO
ALTER TABLE [dbo].[VISITA_TECNICA] CHECK CONSTRAINT [FK_VISITA_TECNICO]
GO
/****** Object:  StoredProcedure [dbo].[ALERTA_ACTUALIZAR_ESTADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ALERTA_ACTUALIZAR_ESTADO]
    @alerta_id INT,
    @estado    VARCHAR(20)
AS
    UPDATE ALERTA_REVISION SET ESTADO = @estado WHERE ID = @alerta_id
GO
/****** Object:  StoredProcedure [dbo].[ALERTA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ALERTA_INSERTAR]
    @equipo_id INT
AS
BEGIN
    INSERT INTO ALERTA_REVISION (EQUIPO_ID, FECHA_GENERACION, ESTADO)
    VALUES (@equipo_id, GETDATE(), 'Pendiente')
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[ALERTA_LISTAR_AUTORIZADAS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ALERTA_LISTAR_AUTORIZADAS]
AS
    SELECT a.ID, a.EQUIPO_ID, e.NOMBRE AS EQUIPO_NOMBRE, a.FECHA_GENERACION, a.ESTADO
    FROM ALERTA_REVISION a
    JOIN EQUIPO e ON e.ID = a.EQUIPO_ID
    WHERE a.ESTADO = 'Autorizada'
    ORDER BY a.FECHA_GENERACION
GO
/****** Object:  StoredProcedure [dbo].[ALERTA_LISTAR_PENDIENTES]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ALERTA_LISTAR_PENDIENTES]
AS
    SELECT a.ID, a.EQUIPO_ID, e.NOMBRE AS EQUIPO_NOMBRE, a.FECHA_GENERACION, a.ESTADO
    FROM ALERTA_REVISION a
    JOIN EQUIPO e ON e.ID = a.EQUIPO_ID
    WHERE a.ESTADO = 'Pendiente'
    ORDER BY a.FECHA_GENERACION
GO
/****** Object:  StoredProcedure [dbo].[ALERTA_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ALERTA_OBTENER]
    @id INT
AS
    SELECT ID, EQUIPO_ID, FECHA_GENERACION, ESTADO FROM ALERTA_REVISION WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[ASISTENCIA_OBTENER_ABIERTA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ASISTENCIA_OBTENER_ABIERTA]
    @usuario_id INT,
    @fecha      DATE
AS
    SELECT ID, USUARIO_ID, FECHA, HORA_INGRESO, HORA_EGRESO
    FROM ASISTENCIA_PERSONAL
    WHERE USUARIO_ID = @usuario_id AND FECHA = @fecha AND HORA_EGRESO IS NULL
GO
/****** Object:  StoredProcedure [dbo].[ASISTENCIA_REGISTRAR_EGRESO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ASISTENCIA_REGISTRAR_EGRESO]
    @id          INT,
    @hora_egreso TIME
AS
    UPDATE ASISTENCIA_PERSONAL SET HORA_EGRESO = @hora_egreso WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[ASISTENCIA_REGISTRAR_INGRESO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ASISTENCIA_REGISTRAR_INGRESO]
    @usuario_id   INT,
    @fecha        DATE,
    @hora_ingreso TIME
AS
BEGIN
    INSERT INTO ASISTENCIA_PERSONAL (USUARIO_ID, FECHA, HORA_INGRESO)
    VALUES (@usuario_id, @fecha, @hora_ingreso)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[BITACORA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BITACORA_INSERTAR]
    @usuario VARCHAR(50),
    @accion  VARCHAR(50)
AS
    INSERT INTO BITACORA (USUARIO, ACCION, FECHA) VALUES (@usuario, @accion, GETDATE())
GO
/****** Object:  StoredProcedure [dbo].[BITACORA_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BITACORA_LISTAR]
AS
    SELECT ID, USUARIO, ACCION, FECHA FROM BITACORA ORDER BY FECHA DESC
GO
/****** Object:  StoredProcedure [dbo].[BITACORA_LISTAR_ACCIONES_DISTINCT]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BITACORA_LISTAR_ACCIONES_DISTINCT]
AS
    SELECT DISTINCT ACCION FROM BITACORA ORDER BY ACCION
GO
/****** Object:  StoredProcedure [dbo].[BITACORA_LISTAR_PAGINADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BITACORA_LISTAR_PAGINADO]
    @usuario      VARCHAR(50)  = NULL,
    @accion       VARCHAR(50)  = NULL,
    @fecha_desde  DATETIME     = NULL,
    @fecha_hasta  DATETIME     = NULL,
    @pagina       INT          = 1,
    @tamanio      INT          = 50
AS
BEGIN
    IF @pagina  < 1 SET @pagina  = 1
    IF @tamanio < 1 SET @tamanio = 50

    SELECT ID, USUARIO, ACCION, FECHA,
           COUNT(*) OVER() AS TOTAL_FILAS
    FROM BITACORA
    WHERE (@usuario     IS NULL OR USUARIO = @usuario)
      AND (@accion      IS NULL OR ACCION  = @accion)
      AND (@fecha_desde IS NULL OR FECHA  >= @fecha_desde)
      AND (@fecha_hasta IS NULL OR FECHA  <  @fecha_hasta)
    ORDER BY FECHA DESC
    OFFSET (@pagina - 1) * @tamanio ROWS
    FETCH NEXT @tamanio ROWS ONLY
END
GO
/****** Object:  StoredProcedure [dbo].[BITACORA_LISTAR_USUARIOS_DISTINCT]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BITACORA_LISTAR_USUARIOS_DISTINCT]
AS
    SELECT DISTINCT USUARIO FROM BITACORA ORDER BY USUARIO
GO
/****** Object:  StoredProcedure [dbo].[CONTROL_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONTROL_LISTAR_TODOS]
AS
    SELECT ID, CLAVE, TEXTO_DEFAULT FROM CONTROL_IDIOMA ORDER BY CLAVE
GO
/****** Object:  StoredProcedure [dbo].[CONTROL_REGISTRAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONTROL_REGISTRAR]
    @clave         VARCHAR(100),
    @texto_default VARCHAR(200)
AS
    IF NOT EXISTS (SELECT 1 FROM CONTROL_IDIOMA WHERE CLAVE = @clave)
        INSERT INTO CONTROL_IDIOMA (CLAVE, TEXTO_DEFAULT) VALUES (@clave, @texto_default)
GO
/****** Object:  StoredProcedure [dbo].[DEMANDA_ESTIMADA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DEMANDA_ESTIMADA_INSERTAR]
    @franja_id                   INT,
    @semana                      DATE,
    @rol_requerido               VARCHAR(30),
    @cantidad_personal_necesario INT,
    @origen_dato                 VARCHAR(20)
AS
BEGIN
    INSERT INTO DEMANDA_ESTIMADA (FRANJA_ID, SEMANA, ROL_REQUERIDO, CANTIDAD_PERSONAL_NECESARIO, ORIGEN_DATO)
    VALUES (@franja_id, @semana, @rol_requerido, @cantidad_personal_necesario, @origen_dato)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[DISPONIBILIDAD_FRANJA_ELIMINAR_POR_DISPONIBILIDAD]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISPONIBILIDAD_FRANJA_ELIMINAR_POR_DISPONIBILIDAD]
    @disponibilidad_id INT
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM DISPONIBILIDAD_FRANJA WHERE DISPONIBILIDAD_ID = @disponibilidad_id;
END
GO
/****** Object:  StoredProcedure [dbo].[DISPONIBILIDAD_FRANJA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISPONIBILIDAD_FRANJA_INSERTAR]
    @disponibilidad_id INT,
    @franja_id         INT
AS
    INSERT INTO DISPONIBILIDAD_FRANJA (DISPONIBILIDAD_ID, FRANJA_ID) VALUES (@disponibilidad_id, @franja_id)
GO
/****** Object:  StoredProcedure [dbo].[DISPONIBILIDAD_FRANJAS_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISPONIBILIDAD_FRANJAS_LISTAR]
    @disponibilidad_id INT
AS
    SELECT f.ID, f.DIA, f.HORA_INICIO, f.HORA_FIN
    FROM FRANJA_HORARIA f
    INNER JOIN DISPONIBILIDAD_FRANJA df ON df.FRANJA_ID = f.ID
    WHERE df.DISPONIBILIDAD_ID = @disponibilidad_id
GO
/****** Object:  StoredProcedure [dbo].[DISPONIBILIDAD_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISPONIBILIDAD_INSERTAR]
    @usuario_id INT,
    @semana     DATE
AS
BEGIN
    INSERT INTO DISPONIBILIDAD (USUARIO_ID, SEMANA) VALUES (@usuario_id, @semana)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[DISPONIBILIDAD_OBTENER_POR_USUARIO_SEMANA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISPONIBILIDAD_OBTENER_POR_USUARIO_SEMANA]
    @usuario_id INT,
    @semana     DATE
AS
    SELECT ID, USUARIO_ID, SEMANA FROM DISPONIBILIDAD WHERE USUARIO_ID = @usuario_id AND SEMANA = @semana
GO
/****** Object:  StoredProcedure [dbo].[DVV_ACTUALIZAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DVV_ACTUALIZAR]
    @tabla   VARCHAR(50),
    @columna VARCHAR(50),
    @dvv     INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM DIGITO_VERIFICADOR_VERTICAL WHERE TABLA = @tabla AND COLUMNA = @columna)
        UPDATE DIGITO_VERIFICADOR_VERTICAL SET DVV = @dvv WHERE TABLA = @tabla AND COLUMNA = @columna
    ELSE
        INSERT INTO DIGITO_VERIFICADOR_VERTICAL (TABLA, COLUMNA, DVV) VALUES (@tabla, @columna, @dvv)
END
GO
/****** Object:  StoredProcedure [dbo].[DVV_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DVV_LISTAR]
    @tabla VARCHAR(50)
AS
    SELECT COLUMNA, DVV FROM DIGITO_VERIFICADOR_VERTICAL WHERE TABLA = @tabla
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_ACTUALIZAR_USO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_ACTUALIZAR_USO]
    @equipo_id  INT,
    @incremento INT
AS
BEGIN
    UPDATE EQUIPO SET USO_ACUMULADO = USO_ACUMULADO + @incremento WHERE ID = @equipo_id
    SELECT USO_ACUMULADO, NIVEL_USO_CRITICO FROM EQUIPO WHERE ID = @equipo_id
END
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_LISTAR_TODOS]
AS
    SELECT ID, NOMBRE, USO_ACUMULADO, NIVEL_USO_CRITICO, ESTADO, TECNICO_HABITUAL_ID
    FROM EQUIPO ORDER BY NOMBRE
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_MARCAR_EN_MANTENIMIENTO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_MARCAR_EN_MANTENIMIENTO]
    @equipo_id INT
AS
    UPDATE EQUIPO SET ESTADO = 'EnMantenimiento' WHERE ID = @equipo_id
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_OBTENER]
    @id INT
AS
    SELECT ID, NOMBRE, USO_ACUMULADO, NIVEL_USO_CRITICO, ESTADO, TECNICO_HABITUAL_ID
    FROM EQUIPO WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_OBTENER_POR_NOMBRE]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_OBTENER_POR_NOMBRE]
    @nombre VARCHAR(100)
AS
    SELECT ID, NOMBRE, USO_ACUMULADO, NIVEL_USO_CRITICO, ESTADO, TECNICO_HABITUAL_ID
    FROM EQUIPO WHERE NOMBRE = @nombre
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_REINICIAR_CONTADOR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_REINICIAR_CONTADOR]
    @equipo_id INT
AS
    UPDATE EQUIPO SET USO_ACUMULADO = 0, ESTADO = 'Operativo' WHERE ID = @equipo_id
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_USO_LOG_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_USO_LOG_INSERTAR]
    @equipo_id  INT,
    @incremento INT
AS
    INSERT INTO EQUIPO_USO_LOG (EQUIPO_ID, FECHA, INCREMENTO) VALUES (@equipo_id, GETDATE(), @incremento)
GO
/****** Object:  StoredProcedure [dbo].[EQUIPO_USO_LOG_ULTIMOS_DIAS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EQUIPO_USO_LOG_ULTIMOS_DIAS]
    @equipo_id INT,
    @dias      INT
AS
    SELECT ISNULL(SUM(INCREMENTO), 0) AS TOTAL, MIN(FECHA) AS DESDE
    FROM EQUIPO_USO_LOG
    WHERE EQUIPO_ID = @equipo_id AND FECHA >= DATEADD(DAY, -@dias, GETDATE())
GO
/****** Object:  StoredProcedure [dbo].[EVALUACION_COBERTURA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EVALUACION_COBERTURA_INSERTAR]
    @franja_id INT,
    @semana    DATE,
    @resultado VARCHAR(20)
AS
BEGIN
    INSERT INTO EVALUACION_COBERTURA (FRANJA_ID, SEMANA, RESULTADO)
    VALUES (@franja_id, @semana, @resultado)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[EVALUACION_COBERTURA_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EVALUACION_COBERTURA_OBTENER]
    @franja_id INT,
    @semana    DATE
AS
    SELECT TOP 1 ID, FRANJA_ID, SEMANA, RESULTADO
    FROM EVALUACION_COBERTURA
    WHERE FRANJA_ID = @franja_id AND SEMANA = @semana
GO
/****** Object:  StoredProcedure [dbo].[EVALUACION_COBERTURA_RESUMEN]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EVALUACION_COBERTURA_RESUMEN]
AS
    SELECT RESULTADO, COUNT(*) AS CANTIDAD FROM EVALUACION_COBERTURA GROUP BY RESULTADO
GO
/****** Object:  StoredProcedure [dbo].[FRANJA_HORARIA_ELIMINAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FRANJA_HORARIA_ELIMINAR]
    @id INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM DISPONIBILIDAD_FRANJA WHERE FRANJA_ID = @id)
       OR EXISTS (SELECT 1 FROM TURNO WHERE FRANJA_ID = @id)
       OR EXISTS (SELECT 1 FROM DEMANDA_ESTIMADA WHERE FRANJA_ID = @id)
       OR EXISTS (SELECT 1 FROM EVALUACION_COBERTURA WHERE FRANJA_ID = @id)
       OR EXISTS (SELECT 1 FROM HISTORIAL_ASISTENCIA_SOCIOS WHERE FRANJA_ID = @id)
    BEGIN
        SELECT 0 AS OK
        RETURN
    END

    DELETE FROM FRANJA_HORARIA WHERE ID = @id
    SELECT 1 AS OK
END
GO
/****** Object:  StoredProcedure [dbo].[FRANJA_HORARIA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FRANJA_HORARIA_INSERTAR]
    @dia            VARCHAR(15),
    @hora_inicio    TIME,
    @hora_fin       TIME,
    @rol_requerido  VARCHAR(30)
AS
BEGIN
    INSERT INTO FRANJA_HORARIA (DIA, HORA_INICIO, HORA_FIN, ROL_REQUERIDO)
    VALUES (@dia, @hora_inicio, @hora_fin, @rol_requerido)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[FRANJA_HORARIA_LISTAR_TODAS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FRANJA_HORARIA_LISTAR_TODAS]
AS
    SELECT ID, DIA, HORA_INICIO, HORA_FIN, ROL_REQUERIDO FROM FRANJA_HORARIA ORDER BY DIA, HORA_INICIO
GO
/****** Object:  StoredProcedure [dbo].[FRANJA_HORARIA_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FRANJA_HORARIA_OBTENER]
    @id INT
AS
    SELECT ID, DIA, HORA_INICIO, HORA_FIN, ROL_REQUERIDO FROM FRANJA_HORARIA WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[GRILLA_CONFIRMAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GRILLA_CONFIRMAR]
    @grilla_id INT
AS
    UPDATE GRILLA_TURNOS SET ESTADO = 'Confirmada' WHERE ID = @grilla_id
GO
/****** Object:  StoredProcedure [dbo].[GRILLA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GRILLA_INSERTAR]
    @administrador_id INT,
    @semana           DATE,
    @estado           VARCHAR(20)
AS
BEGIN
    INSERT INTO GRILLA_TURNOS (ADMINISTRADOR_ID, SEMANA, ESTADO) VALUES (@administrador_id, @semana, @estado)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[GRILLA_MARCAR_COMUNICADA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GRILLA_MARCAR_COMUNICADA]
    @grilla_id INT
AS
    UPDATE GRILLA_TURNOS SET ESTADO = 'Comunicada' WHERE ID = @grilla_id
GO
/****** Object:  StoredProcedure [dbo].[GRILLA_OBTENER_POR_SEMANA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GRILLA_OBTENER_POR_SEMANA]
    @semana DATE
AS
    SELECT TOP 1 ID, ADMINISTRADOR_ID, SEMANA, ESTADO
    FROM GRILLA_TURNOS
    WHERE SEMANA = @semana
    ORDER BY CASE ESTADO WHEN 'Comunicada' THEN 1 WHEN 'Confirmada' THEN 2 ELSE 3 END, ID DESC
GO
/****** Object:  StoredProcedure [dbo].[GRILLA_TURNOS_POR_EMPLEADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GRILLA_TURNOS_POR_EMPLEADO]
    @grilla_id INT
AS
    SELECT t.ID, t.USUARIO_ID, t.FRANJA_ID, t.ROL_REQUERIDO, t.ESTADO
    FROM TURNO t
    WHERE t.GRILLA_ID = @grilla_id AND t.USUARIO_ID IS NOT NULL
    ORDER BY t.USUARIO_ID
GO
/****** Object:  StoredProcedure [dbo].[HISTORIAL_ASISTENCIA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HISTORIAL_ASISTENCIA_INSERTAR]
    @franja_id       INT,
    @fecha           DATE,
    @cantidad_socios INT
AS
BEGIN
    INSERT INTO HISTORIAL_ASISTENCIA_SOCIOS (FRANJA_ID, FECHA, CANTIDAD_SOCIOS)
    VALUES (@franja_id, @fecha, @cantidad_socios)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[HISTORIAL_ASISTENCIA_OBTENER_POR_FRANJA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HISTORIAL_ASISTENCIA_OBTENER_POR_FRANJA]
    @franja_id INT,
    @semanas   INT
AS
    SELECT TOP (@semanas) CANTIDAD_SOCIOS
    FROM HISTORIAL_ASISTENCIA_SOCIOS
    WHERE FRANJA_ID = @franja_id
    ORDER BY FECHA DESC
GO
/****** Object:  StoredProcedure [dbo].[HISTORIAL_ASISTENCIA_OBTENER_POR_FRANJA_Y_SEMANA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HISTORIAL_ASISTENCIA_OBTENER_POR_FRANJA_Y_SEMANA]
    @franja_id    INT,
    @fecha_inicio DATE,
    @fecha_fin    DATE
AS
    SELECT CANTIDAD_SOCIOS
    FROM HISTORIAL_ASISTENCIA_SOCIOS
    WHERE FRANJA_ID = @franja_id
      AND FECHA BETWEEN @fecha_inicio AND @fecha_fin
    ORDER BY FECHA DESC
GO
/****** Object:  StoredProcedure [dbo].[HISTORIAL_ASISTENCIA_SERIE_POR_FRANJA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HISTORIAL_ASISTENCIA_SERIE_POR_FRANJA]
    @franja_id INT
AS
    SELECT FECHA, CANTIDAD_SOCIOS FROM HISTORIAL_ASISTENCIA_SOCIOS WHERE FRANJA_ID = @franja_id ORDER BY FECHA ASC
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_ACTUALIZAR_ESTADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_ACTUALIZAR_ESTADO]
    @id         INT,
    @habilitado BIT
AS
    UPDATE IDIOMA SET HABILITADO = @habilitado WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_ELIMINAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_ELIMINAR]
    @id INT
AS
BEGIN
    SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM IDIOMA WHERE ID = @id AND PREDETERMINADO = 1)
        THROW 50001, 'No se puede eliminar el idioma predeterminado del sistema.', 1;

    IF EXISTS (SELECT 1 FROM USUARIO WHERE IDIOMA_ID = @id)
        THROW 50002, 'No se puede eliminar un idioma que está en uso por algún usuario.', 1;

    BEGIN TRANSACTION;
        DELETE FROM TRADUCCION WHERE IDIOMA_ID = @id;
        DELETE FROM IDIOMA     WHERE ID        = @id;
    COMMIT TRANSACTION;
END

GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_ESTA_EN_USO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_ESTA_EN_USO]
    @id INT
AS
    SELECT COUNT(*) AS TOTAL FROM USUARIO WHERE IDIOMA_ID = @id
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_INSERTAR]
    @nombre     VARCHAR(50),
    @habilitado BIT
AS
BEGIN
    INSERT INTO IDIOMA (NOMBRE, HABILITADO) VALUES (@nombre, @habilitado)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_LISTAR_HABILITADOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_LISTAR_HABILITADOS]
AS
    SELECT ID, NOMBRE, HABILITADO, PREDETERMINADO FROM IDIOMA WHERE HABILITADO = 1 ORDER BY NOMBRE
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_LISTAR_TODOS]
AS
    SELECT ID, NOMBRE, HABILITADO, PREDETERMINADO FROM IDIOMA ORDER BY NOMBRE
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_OBTENER_POR_ID]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_OBTENER_POR_ID]
    @id INT
AS
    SELECT ID, NOMBRE, HABILITADO, PREDETERMINADO FROM IDIOMA WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_RENOMBRAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IDIOMA_RENOMBRAR]
    @id     INT,
    @nombre NVARCHAR(100)
AS
    UPDATE IDIOMA SET NOMBRE = @nombre WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[INFORME_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFORME_INSERTAR]
    @visita_id          INT,
    @resultado          VARCHAR(300),
    @pendiente_repuesto BIT
AS
BEGIN
    INSERT INTO INFORME_MANTENIMIENTO (VISITA_ID, RESULTADO, PENDIENTE_REPUESTO, FECHA_EMISION)
    VALUES (@visita_id, @resultado, @pendiente_repuesto, GETDATE())

    UPDATE VISITA_TECNICA SET ESTADO = 'Realizada' WHERE ID = @visita_id

    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[INFORME_LISTAR_PENDIENTES_CIERRE]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFORME_LISTAR_PENDIENTES_CIERRE]
AS
    SELECT i.ID, i.VISITA_ID, i.RESULTADO, i.PENDIENTE_REPUESTO, i.FECHA_EMISION, a.EQUIPO_ID
    FROM INFORME_MANTENIMIENTO i
    JOIN VISITA_TECNICA v ON v.ID = i.VISITA_ID
    JOIN ALERTA_REVISION a ON a.ID = v.ALERTA_ID
    WHERE i.CERRADO = 0
GO
/****** Object:  StoredProcedure [dbo].[INFORME_MARCAR_CERRADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFORME_MARCAR_CERRADO]
    @id INT
AS
    UPDATE INFORME_MANTENIMIENTO SET CERRADO = 1 WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[INFORME_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFORME_OBTENER]
    @id INT
AS
    SELECT i.ID, i.VISITA_ID, i.RESULTADO, i.PENDIENTE_REPUESTO, i.FECHA_EMISION,
           v.ALERTA_ID, a.EQUIPO_ID
    FROM INFORME_MANTENIMIENTO i
    JOIN VISITA_TECNICA v ON v.ID = i.VISITA_ID
    JOIN ALERTA_REVISION a ON a.ID = v.ALERTA_ID
    WHERE i.ID = @id
GO
/****** Object:  StoredProcedure [dbo].[NOTIFICACION_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[NOTIFICACION_INSERTAR]
    @grilla_id  INT,
    @usuario_id INT,
    @mensaje    VARCHAR(300),
    @estado     VARCHAR(20)
AS
BEGIN
    INSERT INTO NOTIFICACION (GRILLA_ID, USUARIO_ID, MENSAJE, FECHA_ENVIO, ESTADO)
    VALUES (@grilla_id, @usuario_id, @mensaje, GETDATE(), @estado)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[NOTIFICACION_LISTAR_POR_USUARIO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[NOTIFICACION_LISTAR_POR_USUARIO]
    @usuario_id INT
AS
    SELECT ID, GRILLA_ID, USUARIO_ID, MENSAJE, FECHA_ENVIO, ESTADO
    FROM NOTIFICACION
    WHERE USUARIO_ID = @usuario_id
    ORDER BY FECHA_ENVIO DESC
GO
/****** Object:  StoredProcedure [dbo].[PERFIL_CAMBIAR_PADRE]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERFIL_CAMBIAR_PADRE]
    @id       INT,
    @padre_id INT = NULL
AS
    UPDATE NODO_PERMISO SET PADRE_ID = @padre_id WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[PERFIL_ELIMINAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERFIL_ELIMINAR]
    @id INT
AS
BEGIN
    DECLARE @ids TABLE (ID INT)
    ;WITH Descendientes AS (
        SELECT ID FROM NODO_PERMISO WHERE ID = @id
        UNION ALL
        SELECT np.ID FROM NODO_PERMISO np
            INNER JOIN Descendientes d ON np.PADRE_ID = d.ID
    )
    INSERT INTO @ids SELECT ID FROM Descendientes

    DELETE FROM USUARIO_PERFIL WHERE PERFIL_ID  IN (SELECT ID FROM @ids)
    DELETE FROM ROL_PERMISO    WHERE ROL_ID      IN (SELECT ID FROM @ids)
    DELETE FROM NODO_PERMISO   WHERE ID          IN (SELECT ID FROM @ids)
END
GO
/****** Object:  StoredProcedure [dbo].[PERFIL_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERFIL_INSERTAR]
    @nombre   VARCHAR(100),
    @tipo     VARCHAR(10),
    @padre_id INT = NULL
AS
BEGIN
    INSERT INTO NODO_PERMISO (NOMBRE, TIPO, PADRE_ID) VALUES (@nombre, @tipo, @padre_id)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[PERFIL_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERFIL_LISTAR_TODOS]
AS
    SELECT ID, NOMBRE, TIPO, PADRE_ID, PROTEGIDO
    FROM NODO_PERMISO
    WHERE TIPO = 'PERFIL'
    ORDER BY ID
GO
/****** Object:  StoredProcedure [dbo].[PERFIL_TIENE_USUARIOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERFIL_TIENE_USUARIOS]
    @rol_id INT
AS
BEGIN
    DECLARE @ids TABLE (ID INT)
    ;WITH Descendientes AS (
        SELECT ID FROM NODO_PERMISO WHERE ID = @rol_id AND TIPO = 'PERFIL'
        UNION ALL
        SELECT np.ID FROM NODO_PERMISO np
            INNER JOIN Descendientes d ON np.PADRE_ID = d.ID
        WHERE np.TIPO = 'PERFIL'
    )
    INSERT INTO @ids SELECT ID FROM Descendientes
    SELECT COUNT(*) AS TOTAL FROM USUARIO_PERFIL WHERE PERFIL_ID IN (SELECT ID FROM @ids)
END
GO
/****** Object:  StoredProcedure [dbo].[PERMISO_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERMISO_LISTAR_TODOS]
AS
    SELECT ID, NOMBRE
    FROM PERMISO
    ORDER BY NOMBRE
GO
/****** Object:  StoredProcedure [dbo].[ROL_CAMBIAR_PADRE]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_CAMBIAR_PADRE]
    @id       INT,
    @padre_id INT = NULL
AS
    UPDATE ROL SET PADRE_ID = @padre_id WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[ROL_ELIMINAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_ELIMINAR]
    @id INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM ROL WHERE ID = @id AND PROTEGIDO = 1)
    BEGIN
        RAISERROR('Este rol es del sistema y no puede eliminarse.', 16, 1)
        RETURN
    END

    DECLARE @ids TABLE (ID INT)
    ;WITH Descendientes AS (
        SELECT ID FROM ROL WHERE ID = @id
        UNION ALL
        SELECT r.ID FROM ROL r
            INNER JOIN Descendientes d ON r.PADRE_ID = d.ID
    )
    INSERT INTO @ids SELECT ID FROM Descendientes

    DELETE FROM USUARIO_PERFIL WHERE PERFIL_ID IN (SELECT ID FROM @ids)
    DELETE FROM ROL_PERMISO    WHERE ROL_ID    IN (SELECT ID FROM @ids)
    DELETE FROM ROL            WHERE ID        IN (SELECT ID FROM @ids)
END
GO
/****** Object:  StoredProcedure [dbo].[ROL_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_INSERTAR]
    @nombre   VARCHAR(100),
    @padre_id INT = NULL
AS
BEGIN
    INSERT INTO ROL (NOMBRE, PADRE_ID) VALUES (@nombre, @padre_id)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[ROL_LISTAR_PARA_COMBO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_LISTAR_PARA_COMBO]
AS
    SELECT ID, NOMBRE FROM ROL ORDER BY NOMBRE
GO
/****** Object:  StoredProcedure [dbo].[ROL_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_LISTAR_TODOS]
AS
    SELECT ID, NOMBRE, PADRE_ID, PROTEGIDO
    FROM ROL
    ORDER BY ID
GO
/****** Object:  StoredProcedure [dbo].[ROL_PERMISO_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_PERMISO_INSERTAR]
    @rol_id     INT,
    @permiso_id INT
AS
    IF NOT EXISTS (SELECT 1 FROM ROL_PERMISO WHERE ROL_ID = @rol_id AND PERMISO_ID = @permiso_id)
        INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID) VALUES (@rol_id, @permiso_id)
GO
/****** Object:  StoredProcedure [dbo].[ROL_PERMISO_LIMPIAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_PERMISO_LIMPIAR]
    @rol_id INT
AS
    DELETE FROM ROL_PERMISO WHERE ROL_ID = @rol_id
GO
/****** Object:  StoredProcedure [dbo].[ROL_PERMISO_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_PERMISO_LISTAR]
    @rol_id INT
AS
    SELECT PERMISO_ID FROM ROL_PERMISO WHERE ROL_ID = @rol_id
GO
/****** Object:  StoredProcedure [dbo].[ROL_PERMISO_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_PERMISO_LISTAR_TODOS]
AS
    SELECT rp.ROL_ID, rp.PERMISO_ID, p.NOMBRE
    FROM ROL_PERMISO rp
    JOIN PERMISO p ON p.ID = rp.PERMISO_ID
GO
/****** Object:  StoredProcedure [dbo].[ROL_TIENE_USUARIOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ROL_TIENE_USUARIOS]
    @rol_id INT
AS
BEGIN
    DECLARE @ids TABLE (ID INT)
    ;WITH Descendientes AS (
        SELECT ID FROM ROL WHERE ID = @rol_id
        UNION ALL
        SELECT r.ID FROM ROL r
            INNER JOIN Descendientes d ON r.PADRE_ID = d.ID
    )
    INSERT INTO @ids SELECT ID FROM Descendientes

    SELECT
        (SELECT COUNT(*) FROM USUARIO_PERFIL WHERE PERFIL_ID IN (SELECT ID FROM @ids))
      + (SELECT COUNT(*) FROM USUARIO        WHERE ROL_ID    IN (SELECT ID FROM @ids))
      AS TOTAL
END
GO
/****** Object:  StoredProcedure [dbo].[TRADUCCION_GUARDAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TRADUCCION_GUARDAR]
    @idioma_id  INT,
    @control_id INT,
    @texto      VARCHAR(200)
AS
BEGIN
    IF @idioma_id IS NULL OR @control_id IS NULL
    BEGIN
        RAISERROR('idioma_id o control_id es NULL — verificar que existan en sus tablas', 16, 1)
        RETURN
    END

    IF EXISTS (SELECT 1 FROM TRADUCCION WHERE IDIOMA_ID = @idioma_id AND CONTROL_ID = @control_id)
        UPDATE TRADUCCION SET TEXTO = @texto
        WHERE IDIOMA_ID = @idioma_id AND CONTROL_ID = @control_id
    ELSE
        INSERT INTO TRADUCCION (IDIOMA_ID, CONTROL_ID, TEXTO) VALUES (@idioma_id, @control_id, @texto)
END
GO
/****** Object:  StoredProcedure [dbo].[TRADUCCION_LISTAR_CONTROLES]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TRADUCCION_LISTAR_CONTROLES]
    @idioma_id INT
AS
    SELECT ci.ID, ci.CLAVE, ci.TEXTO_DEFAULT,
           ISNULL(t.TEXTO, '') AS TEXTO_TRADUCCION
    FROM CONTROL_IDIOMA ci
    LEFT JOIN TRADUCCION t ON t.CONTROL_ID = ci.ID AND t.IDIOMA_ID = @idioma_id
    ORDER BY ci.CLAVE
GO
/****** Object:  StoredProcedure [dbo].[TRADUCCION_LISTAR_POR_IDIOMA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TRADUCCION_LISTAR_POR_IDIOMA]
    @idioma_id INT
AS
    SELECT ci.CLAVE, t.TEXTO
    FROM CONTROL_IDIOMA ci
    LEFT JOIN TRADUCCION t ON t.CONTROL_ID = ci.ID AND t.IDIOMA_ID = @idioma_id
    WHERE t.TEXTO IS NOT NULL
GO
/****** Object:  StoredProcedure [dbo].[TURNO_ACTUALIZAR_ASIGNACION]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_ACTUALIZAR_ASIGNACION]
    @turno_id   INT,
    @usuario_id INT = NULL,
    @estado     VARCHAR(20)
AS
    UPDATE TURNO SET USUARIO_ID = @usuario_id, ESTADO = @estado WHERE ID = @turno_id
GO
/****** Object:  StoredProcedure [dbo].[TURNO_BUSCAR_COMPATIBLES]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_BUSCAR_COMPATIBLES]
    @rol_requerido VARCHAR(30),
    @franja_id     INT,
    @grilla_id     INT
AS
    SELECT u.ID, u.USUARIO, u.NOMBRE, u.APELLIDO, u.LIMITE_HORAS_SEMANALES
    FROM USUARIO u
    JOIN ROL r ON r.ID = u.ROL_ID
    WHERE r.NOMBRE = @rol_requerido
      AND u.ID NOT IN (
          SELECT USUARIO_ID FROM TURNO
          WHERE GRILLA_ID = @grilla_id AND FRANJA_ID = @franja_id AND USUARIO_ID IS NOT NULL
      )
GO
/****** Object:  StoredProcedure [dbo].[TURNO_CONTAR_ASIGNADOS_POR_FRANJA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_CONTAR_ASIGNADOS_POR_FRANJA]
    @grilla_id INT,
    @franja_id INT
AS
    SELECT COUNT(*) AS CANTIDAD
    FROM TURNO
    WHERE GRILLA_ID = @grilla_id AND FRANJA_ID = @franja_id AND USUARIO_ID IS NOT NULL
GO
/****** Object:  StoredProcedure [dbo].[TURNO_HORAS_ASIGNADAS_SEMANA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_HORAS_ASIGNADAS_SEMANA]
    @usuario_id INT,
    @grilla_id  INT
AS
    SELECT ISNULL(SUM(DATEDIFF(MINUTE, f.HORA_INICIO, f.HORA_FIN)) / 60.0, 0) AS HORAS
    FROM TURNO t
    JOIN FRANJA_HORARIA f ON f.ID = t.FRANJA_ID
    WHERE t.USUARIO_ID = @usuario_id AND t.GRILLA_ID = @grilla_id
GO
/****** Object:  StoredProcedure [dbo].[TURNO_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_INSERTAR]
    @grilla_id     INT,
    @franja_id     INT,
    @usuario_id    INT = NULL,
    @rol_requerido VARCHAR(30),
    @estado        VARCHAR(20)
AS
BEGIN
    INSERT INTO TURNO (GRILLA_ID, FRANJA_ID, USUARIO_ID, ROL_REQUERIDO, ESTADO)
    VALUES (@grilla_id, @franja_id, @usuario_id, @rol_requerido, @estado)
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[TURNO_LISTAR_PENDIENTES_POR_ROL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_LISTAR_PENDIENTES_POR_ROL]
    @rol_requerido VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID, GRILLA_ID, FRANJA_ID, USUARIO_ID, ROL_REQUERIDO, ESTADO
    FROM TURNO
    WHERE ESTADO = 'PendienteCobertura' AND ROL_REQUERIDO = @rol_requerido;
END
GO
/****** Object:  StoredProcedure [dbo].[TURNO_LISTAR_POR_GRILLA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_LISTAR_POR_GRILLA]
    @grilla_id INT
AS
    SELECT ID, GRILLA_ID, FRANJA_ID, USUARIO_ID, ROL_REQUERIDO, ESTADO
    FROM TURNO WHERE GRILLA_ID = @grilla_id
GO
/****** Object:  StoredProcedure [dbo].[TURNO_LISTAR_POR_USUARIO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_LISTAR_POR_USUARIO]
    @usuario_id INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID, GRILLA_ID, FRANJA_ID, USUARIO_ID, ROL_REQUERIDO, ESTADO
    FROM TURNO
    WHERE USUARIO_ID = @usuario_id
      AND ESTADO = 'Asignado';
END
GO
/****** Object:  StoredProcedure [dbo].[TURNO_TOMAR_COBERTURA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TURNO_TOMAR_COBERTURA]
    @turno_id INT,
    @usuario_id INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TURNO
    SET USUARIO_ID = @usuario_id, ESTADO = 'Asignado'
    WHERE ID = @turno_id AND ESTADO = 'PendienteCobertura';

    SELECT @@ROWCOUNT AS FilasActualizadas;
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_ACTUALIZAR_DATOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_ACTUALIZAR_DATOS]
    @id       INT,
    @nombre   VARCHAR(50),
    @apellido VARCHAR(50),
    @telefono VARCHAR(30) = NULL,
    @email    VARCHAR(100) = NULL
AS
    UPDATE USUARIO
    SET NOMBRE = @nombre, APELLIDO = @apellido, TELEFONO = @telefono, EMAIL = @email
    WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_ACTUALIZAR_DVH]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_ACTUALIZAR_DVH]
    @id  INT,
    @dvh INT
AS
    UPDATE USUARIO SET DVH = @dvh WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_ACTUALIZAR_IDIOMA]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_ACTUALIZAR_IDIOMA]
    @id        INT,
    @idioma_id INT
AS
    UPDATE USUARIO SET IDIOMA_ID = @idioma_id WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_APLICAR_ESTADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_APLICAR_ESTADO]
    @id                INT,
    @rol               VARCHAR(20),
    @bloqueado         BIT,
    @intentos_fallidos INT,
    @rol_id            INT = NULL
AS
    UPDATE USUARIO
    SET ROL = @rol, BLOQUEADO = @bloqueado, INTENTOS_FALLIDOS = @intentos_fallidos,
        ROL_ID = ISNULL(@rol_id, ROL_ID)
    WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_CAMBIAR_PASS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_CAMBIAR_PASS]
    @usuario VARCHAR(50),
    @pass    VARCHAR(64)
AS
    UPDATE USUARIO SET PASS = @pass WHERE USUARIO = @usuario
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_CREAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_CREAR]
    @usuario  VARCHAR(50),
    @pass     VARCHAR(64),
    @rol_id   INT,
    @nombre   VARCHAR(50) = NULL,
    @apellido VARCHAR(50) = NULL,
    @telefono VARCHAR(30) = NULL,
    @email    VARCHAR(100) = NULL
AS
BEGIN
    IF EXISTS (SELECT 1 FROM USUARIO WHERE USUARIO = @usuario)
    BEGIN
        SELECT 0 AS OK
        RETURN
    END

    DECLARE @rolNombre VARCHAR(20) = (SELECT CASE WHEN PROTEGIDO = 1 THEN 'admin' ELSE 'usuario' END
                                       FROM ROL WHERE ID = @rol_id)

    INSERT INTO USUARIO (USUARIO, PASS, ROL, ROL_ID, NOMBRE, APELLIDO, TELEFONO, EMAIL)
    VALUES (@usuario, @pass, ISNULL(@rolNombre, 'usuario'), @rol_id, @nombre, @apellido, @telefono, @email)

    DECLARE @nuevoId INT = SCOPE_IDENTITY()

    -- El rol elegido en el combo también se asigna como perfil,
    -- así el usuario nuevo ya hereda los permisos correspondientes
    -- sin requerir el paso manual de "Modificar perfiles".
    IF NOT EXISTS (SELECT 1 FROM USUARIO_PERFIL WHERE USUARIO_ID = @nuevoId AND PERFIL_ID = @rol_id)
        INSERT INTO USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (@nuevoId, @rol_id)

    SELECT 1 AS OK
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_DESBLOQUEAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_DESBLOQUEAR]
    @usuario VARCHAR(50)
AS
    UPDATE USUARIO SET BLOQUEADO = 0, INTENTOS_FALLIDOS = 0 WHERE USUARIO = @usuario
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_ELIMINAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_ELIMINAR]
    @id INT
AS
BEGIN
    DELETE FROM USUARIO_PERFIL WHERE USUARIO_ID = @id
    DELETE FROM USUARIO         WHERE ID         = @id
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_HISTORIAL_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_HISTORIAL_INSERTAR]
    @usuario_id        INT,
    @usuario_login     VARCHAR(50),
    @rol               VARCHAR(20),
    @bloqueado         BIT,
    @intentos_fallidos INT,
    @perfiles          VARCHAR(500),
    @realizado_por     VARCHAR(50),
    @tipo_cambio       VARCHAR(25),
    @version_origen    INT,
    @nombre            VARCHAR(50) = NULL,
    @apellido          VARCHAR(50) = NULL,
    @telefono          VARCHAR(30) = NULL,
    @email             VARCHAR(100) = NULL,
    @rol_id            INT = NULL
AS
    INSERT INTO USUARIO_HISTORIAL
        (USUARIO_ID, USUARIO_LOGIN, ROL, BLOQUEADO, INTENTOS_FALLIDOS,
         PERFILES, REALIZADO_POR, TIPO_CAMBIO, VERSION_ORIGEN, NOMBRE, APELLIDO, TELEFONO, EMAIL, ROL_ID)
    VALUES
        (@usuario_id, @usuario_login, @rol, @bloqueado, @intentos_fallidos,
         @perfiles, @realizado_por, @tipo_cambio, @version_origen, @nombre, @apellido, @telefono, @email, @rol_id)
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_HISTORIAL_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_HISTORIAL_LISTAR]
    @usuario_id INT
AS
    SELECT ID, USUARIO_ID, USUARIO_LOGIN, ROL, ROL_ID, BLOQUEADO, INTENTOS_FALLIDOS,
           PERFILES, FECHA_CAMBIO, REALIZADO_POR, TIPO_CAMBIO, VERSION_ORIGEN,
           NOMBRE, APELLIDO, TELEFONO, EMAIL
    FROM USUARIO_HISTORIAL
    WHERE USUARIO_ID = @usuario_id
    ORDER BY ID DESC
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_HISTORIAL_LISTAR_PAGINADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_HISTORIAL_LISTAR_PAGINADO]
    @usuario_id INT,
    @pagina     INT = 1,
    @tamanio    INT = 25
AS
BEGIN
    IF @pagina  < 1 SET @pagina  = 1
    IF @tamanio < 1 SET @tamanio = 25

    SELECT ID, USUARIO_ID, USUARIO_LOGIN, ROL, ROL_ID, BLOQUEADO, INTENTOS_FALLIDOS,
           PERFILES, FECHA_CAMBIO, REALIZADO_POR, TIPO_CAMBIO, VERSION_ORIGEN,
           NOMBRE, APELLIDO, TELEFONO, EMAIL,
           COUNT(*) OVER() AS TOTAL_FILAS
    FROM USUARIO_HISTORIAL
    WHERE USUARIO_ID = @usuario_id
    ORDER BY ID DESC
    OFFSET (@pagina - 1) * @tamanio ROWS
    FETCH NEXT @tamanio ROWS ONLY
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_HISTORIAL_OBTENER]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_HISTORIAL_OBTENER]
    @id INT
AS
    SELECT ID, USUARIO_ID, USUARIO_LOGIN, ROL, ROL_ID, BLOQUEADO, INTENTOS_FALLIDOS,
           PERFILES, FECHA_CAMBIO, REALIZADO_POR, TIPO_CAMBIO, VERSION_ORIGEN,
           NOMBRE, APELLIDO, TELEFONO, EMAIL
    FROM USUARIO_HISTORIAL WHERE ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_INCREMENTAR_INTENTOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_INCREMENTAR_INTENTOS]
    @usuario VARCHAR(50)
AS
BEGIN
    UPDATE USUARIO
    SET INTENTOS_FALLIDOS = INTENTOS_FALLIDOS + 1,
        BLOQUEADO = CASE WHEN INTENTOS_FALLIDOS + 1 >= 3 THEN 1 ELSE BLOQUEADO END
    WHERE USUARIO = @usuario

    SELECT BLOQUEADO FROM USUARIO WHERE USUARIO = @usuario
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR_PAGINADO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_LISTAR_PAGINADO]
    @busqueda VARCHAR(100) = NULL,
    @pagina   INT          = 1,
    @tamanio  INT          = 25
AS
BEGIN
    IF @pagina  < 1 SET @pagina  = 1
    IF @tamanio < 1 SET @tamanio = 25

    SELECT u.ID, u.USUARIO, u.ROL, u.ROL_ID, r.NOMBRE AS ROL_NOMBRE, u.BLOQUEADO,
           u.NOMBRE, u.APELLIDO, u.TELEFONO, u.EMAIL,
           COUNT(*) OVER() AS TOTAL_FILAS
    FROM USUARIO u
    LEFT JOIN ROL r ON r.ID = u.ROL_ID
    WHERE (@busqueda IS NULL
           OR u.USUARIO  LIKE '%' + @busqueda + '%'
           OR u.NOMBRE   LIKE '%' + @busqueda + '%'
           OR u.APELLIDO LIKE '%' + @busqueda + '%')
    ORDER BY u.USUARIO
    OFFSET (@pagina - 1) * @tamanio ROWS
    FETCH NEXT @tamanio ROWS ONLY
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR_PARA_INTEGRIDAD]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_LISTAR_PARA_INTEGRIDAD]
AS
    SELECT ID, USUARIO, PASS, INTENTOS_FALLIDOS, BLOQUEADO, ROL, DVH
    FROM USUARIO ORDER BY ID
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR_POR_ROL]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_LISTAR_POR_ROL]
    @rol VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID, USUARIO, NOMBRE, APELLIDO, EMAIL, TELEFONO
    FROM USUARIO
    WHERE ROL = @rol;
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_LISTAR_TODOS]
AS
    SELECT u.ID, u.USUARIO, u.ROL, u.ROL_ID, r.NOMBRE AS ROL_NOMBRE, u.BLOQUEADO,
           u.NOMBRE, u.APELLIDO, u.TELEFONO, u.EMAIL
    FROM USUARIO u
    LEFT JOIN ROL r ON r.ID = u.ROL_ID
    ORDER BY u.USUARIO
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LOGIN]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_LOGIN]
    @usuario VARCHAR(64),
    @pass    VARCHAR(64)
AS
    SELECT u.ID, u.USUARIO, u.ROL, u.ROL_ID, r.NOMBRE AS ROL_NOMBRE, u.IDIOMA_ID
    FROM USUARIO u
    LEFT JOIN ROL r ON r.ID = u.ROL_ID
    WHERE u.USUARIO = @usuario AND u.PASS = @pass
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_OBTENER_ID_POR_NOMBRE]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_OBTENER_ID_POR_NOMBRE]
    @usuario VARCHAR(50)
AS
    SELECT ID FROM USUARIO WHERE USUARIO = @usuario
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_OBTENER_POR_ID]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_OBTENER_POR_ID]
    @id INT
AS
    SELECT u.ID, u.USUARIO, u.ROL, u.ROL_ID, r.NOMBRE AS ROL_NOMBRE,
           u.INTENTOS_FALLIDOS, u.BLOQUEADO, u.NOMBRE, u.APELLIDO, u.TELEFONO, u.EMAIL,
           u.LIMITE_HORAS_SEMANALES
    FROM USUARIO u
    LEFT JOIN ROL r ON r.ID = u.ROL_ID
    WHERE u.ID = @id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERFIL_ASIGNAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_PERFIL_ASIGNAR]
    @usuario_id INT,
    @perfil_id  INT
AS
    INSERT INTO USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (@usuario_id, @perfil_id)
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERFIL_BORRAR_TODOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_PERFIL_BORRAR_TODOS]
    @usuario_id INT
AS
    DELETE FROM USUARIO_PERFIL WHERE USUARIO_ID = @usuario_id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERFIL_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_PERFIL_LISTAR]
    @usuario_id INT
AS
    SELECT PERFIL_ID FROM USUARIO_PERFIL WHERE USUARIO_ID = @usuario_id
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERFIL_LISTAR_ACTIVOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_PERFIL_LISTAR_ACTIVOS]
AS
    SELECT u.ID AS USUARIO_ID, up.PERFIL_ID
    FROM USUARIO u
    LEFT JOIN USUARIO_PERFIL up ON up.USUARIO_ID = u.ID
    WHERE u.BLOQUEADO = 0

GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERMISOS_LISTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_PERMISOS_LISTAR]
    @usuario_id INT
AS
BEGIN
    SELECT DISTINCT p.NOMBRE
    FROM USUARIO_PERFIL up
    JOIN ROL_PERMISO rp ON rp.ROL_ID = up.PERFIL_ID
    JOIN PERMISO     p  ON p.ID      = rp.PERMISO_ID
    WHERE up.USUARIO_ID = @usuario_id
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_RESETEAR_INTENTOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_RESETEAR_INTENTOS]
    @usuario VARCHAR(50)
AS
    UPDATE USUARIO SET INTENTOS_FALLIDOS = 0 WHERE USUARIO = @usuario
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_VERIFICAR_BLOQUEO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USUARIO_VERIFICAR_BLOQUEO]
    @usuario VARCHAR(50)
AS
    SELECT BLOQUEADO FROM USUARIO WHERE USUARIO = @usuario
GO
/****** Object:  StoredProcedure [dbo].[VISITA_INSERTAR]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VISITA_INSERTAR]
    @alerta_id        INT,
    @tecnico_id       INT,
    @fecha_coordinada DATETIME
AS
BEGIN
    INSERT INTO VISITA_TECNICA (ALERTA_ID, TECNICO_ID, FECHA_COORDINADA, ESTADO)
    VALUES (@alerta_id, @tecnico_id, @fecha_coordinada, 'Coordinada')
    SELECT SCOPE_IDENTITY() AS ID
END
GO
/****** Object:  StoredProcedure [dbo].[VISITA_LISTAR_PENDIENTES_TECNICO]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VISITA_LISTAR_PENDIENTES_TECNICO]
    @tecnico_id INT
AS
    SELECT ID, ALERTA_ID, TECNICO_ID, FECHA_COORDINADA, ESTADO
    FROM VISITA_TECNICA
    WHERE TECNICO_ID = @tecnico_id AND ESTADO = 'Coordinada'
GO
/****** Object:  StoredProcedure [dbo].[VISITA_TECNICOS_ALTERNATIVOS]    Script Date: 04/10/2026 12:15:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VISITA_TECNICOS_ALTERNATIVOS]
AS
    SELECT u.ID, u.USUARIO, u.NOMBRE, u.APELLIDO, u.TELEFONO, u.EMAIL
    FROM USUARIO u
    JOIN ROL r ON r.ID = u.ROL_ID
    WHERE r.NOMBRE = 'Tecnico'
GO
/****** Datos iniciales (idempotente: solo inserta lo que falta) ******/
IF NOT EXISTS (SELECT 1 FROM IDIOMA WHERE NOMBRE = 'Español')
    INSERT INTO IDIOMA (NOMBRE, HABILITADO, PREDETERMINADO) VALUES ('Español', 1, 1)
IF NOT EXISTS (SELECT 1 FROM IDIOMA WHERE NOMBRE = 'Inglés')
    INSERT INTO IDIOMA (NOMBRE, HABILITADO, PREDETERMINADO) VALUES ('Inglés', 1, 0)
IF NOT EXISTS (SELECT 1 FROM IDIOMA WHERE NOMBRE = 'Portugues')
    INSERT INTO IDIOMA (NOMBRE, HABILITADO, PREDETERMINADO) VALUES ('Portugues', 1, 0)
GO
INSERT INTO PERMISO (NOMBRE)
SELECT v.NOMBRE
FROM (VALUES ('Ver bitácora'), ('Administrar usuarios'), ('Gestión de roles'),
             ('Gestión de idiomas'), ('Cambiar contraseña'), ('Generar grilla de turnos')) v(NOMBRE)
WHERE NOT EXISTS (SELECT 1 FROM PERMISO p WHERE p.NOMBRE = v.NOMBRE)
GO
IF NOT EXISTS (SELECT 1 FROM ROL WHERE NOMBRE = 'Administrador')
    INSERT INTO ROL (NOMBRE, PADRE_ID, PROTEGIDO) VALUES ('Administrador', NULL, 1)
ELSE
    UPDATE ROL SET PROTEGIDO = 1 WHERE NOMBRE = 'Administrador'

INSERT INTO ROL (NOMBRE, PADRE_ID, PROTEGIDO)
SELECT v.NOMBRE, NULL, 0
FROM (VALUES ('Usuario'), ('Sala'), ('Recepcion'), ('Tecnico')) v(NOMBRE)
WHERE NOT EXISTS (SELECT 1 FROM ROL r WHERE r.NOMBRE = v.NOMBRE)
GO
DECLARE @rolAdminId INT = (SELECT ID FROM ROL WHERE NOMBRE = 'Administrador')
INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID)
SELECT @rolAdminId, p.ID FROM PERMISO p
WHERE NOT EXISTS (SELECT 1 FROM ROL_PERMISO rp WHERE rp.ROL_ID = @rolAdminId AND rp.PERMISO_ID = p.ID)

DECLARE @permCambiarPassId INT = (SELECT ID FROM PERMISO WHERE NOMBRE = 'Cambiar contraseña')
INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID)
SELECT r.ID, @permCambiarPassId FROM ROL r
WHERE r.NOMBRE IN ('Usuario', 'Sala', 'Recepcion', 'Tecnico')
  AND NOT EXISTS (SELECT 1 FROM ROL_PERMISO rp WHERE rp.ROL_ID = r.ID AND rp.PERMISO_ID = @permCambiarPassId)
GO
DECLARE @rolAdminId INT = (SELECT ID FROM ROL WHERE NOMBRE = 'Administrador')
IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE USUARIO = 'admin')
    INSERT INTO USUARIO (USUARIO, PASS, ROL, ROL_ID)
    VALUES ('admin', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'admin', @rolAdminId)

DECLARE @adminUserId INT = (SELECT ID FROM USUARIO WHERE USUARIO = 'admin')
IF NOT EXISTS (SELECT 1 FROM USUARIO_PERFIL WHERE USUARIO_ID = @adminUserId AND PERFIL_ID = @rolAdminId)
    INSERT INTO USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (@adminUserId, @rolAdminId)
GO
USE [master]
GO
ALTER DATABASE [BDCAPAS] SET  READ_WRITE
GO
