USE [BDCAPAS]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[APELLIDO] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](50) NULL,
	[PASS] [varchar](64) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_BORRAR]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PERSONA_BORRAR]
    @ID INT
AS
    DELETE FROM PERSONA WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_EDITAR]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PERSONA_EDITAR]
    @ID  INT,
    @nom VARCHAR(50),
    @ape VARCHAR(50)
AS
    UPDATE PERSONA SET NOMBRE = @nom, APELLIDO = @ape WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_INSERTAR]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PERSONA_INSERTAR]
    @nom VARCHAR(50),
    @ape VARCHAR(50)
AS
    INSERT INTO PERSONA (NOMBRE, APELLIDO) VALUES (@nom, @ape)
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_LISTAR]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PERSONA_LISTAR]
AS
    SELECT ID, NOMBRE, APELLIDO FROM PERSONA
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LOGIN]    Script Date: 27/04/2026 1:27:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USUARIO_LOGIN]
    @usuario VARCHAR(64),
    @pass    VARCHAR(64)
AS
    SELECT ID, USUARIO 
    FROM USUARIO
    WHERE USUARIO = @usuario AND PASS = @pass
GO
/****** Datos iniciales ******/
INSERT INTO USUARIO (USUARIO, PASS) 
VALUES ('admin', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4')
GO