USE [BDCAPAS]
GO
SET NOCOUNT ON;

DECLARE @textos TABLE (CLAVE VARCHAR(100) PRIMARY KEY, ES NVARCHAR(400), EN NVARCHAR(400), PT NVARCHAR(400));
INSERT INTO @textos (CLAVE, ES, EN, PT) VALUES
    (N'frmAdminUsuarios', N'Administración de usuarios', N'User administration', N'Administração de usuários'),
    (N'frmAdminUsuarios.btnBuscar', N'Buscar', N'Search', N'Buscar'),
    (N'frmAdminUsuarios.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmAdminUsuarios.btnDesbloquear', N'Desbloquear seleccionado', N'Unlock selected', N'Desbloquear selecionado'),
    (N'frmAdminUsuarios.btnEditarDatos', N'Editar datos', N'Edit details', N'Editar dados'),
    (N'frmAdminUsuarios.btnEliminar', N'Eliminar usuario', N'Delete user', N'Excluir usuário'),
    (N'frmAdminUsuarios.btnHistorial', N'Ver historial', N'View history', N'Ver histórico'),
    (N'frmAdminUsuarios.btnModificarPerfiles', N'Modificar perfiles', N'Edit roles', N'Alterar perfis'),
    (N'frmAdminUsuarios.btnNuevo', N'Nuevo usuario', N'New user', N'Novo usuário'),
    (N'frmAdminUsuarios.btnPaginaAnterior', N'< Anterior', N'< Previous', N'< Anterior'),
    (N'frmAdminUsuarios.btnPaginaSiguiente', N'Siguiente >', N'Next >', N'Próxima >'),
    (N'frmAdminUsuarios.btnRefrescar', N'Refrescar', N'Refresh', N'Atualizar'),
    (N'frmAdminUsuarios.lblTitulo', N'Gestión de usuarios', N'User management', N'Gestão de usuários'),
    (N'frmAjustarPorAusencia', N'Ajustar grilla por ausencia', N'Adjust schedule for absence', N'Ajustar escala por ausência'),
    (N'frmAjustarPorAusencia.btnBuscar', N'Buscar grilla', N'Find schedule', N'Buscar escala'),
    (N'frmAjustarPorAusencia.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmAjustarPorAusencia.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmAjustarPorAusencia.lblSemana', N'Fecha (dentro de la semana):', N'Date (within the week):', N'Data (dentro da semana):'),
    (N'frmAjustarPorAusencia.lblTitulo', N'Ajustar grilla por ausencia imprevista', N'Adjust schedule for an unexpected absence', N'Ajustar escala por ausência imprevista'),
    (N'frmAsignarEmpleado', N'Asignar empleado', N'Assign employee', N'Atribuir funcionário'),
    (N'frmAsignarEmpleado.btnAsignar', N'Asignar', N'Assign', N'Atribuir'),
    (N'frmAsignarEmpleado.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmAsignarEmpleado.btnSinCobertura', N'Sin cobertura', N'No coverage', N'Sem cobertura'),
    (N'frmAsignarPerfiles', N'Asignar roles al usuario', N'Assign roles to user', N'Atribuir perfis ao usuário'),
    (N'frmAsignarPerfiles.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmAsignarPerfiles.btnGuardar', N'Guardar', N'Save', N'Salvar'),
    (N'frmBitacora', N'Bitácora', N'Audit log', N'Log de auditoria'),
    (N'frmBitacora.btnFiltrar', N'Filtrar', N'Filter', N'Filtrar'),
    (N'frmBitacora.btnLimpiar', N'Limpiar', N'Clear', N'Limpar'),
    (N'frmBitacora.btnPaginaAnterior', N'< Anterior', N'< Previous', N'< Anterior'),
    (N'frmBitacora.btnPaginaSiguiente', N'Siguiente >', N'Next >', N'Próxima >'),
    (N'frmBitacora.lblAccion', N'Acción:', N'Action:', N'Ação:'),
    (N'frmBitacora.lblDesde', N'Desde:', N'From:', N'De:'),
    (N'frmBitacora.lblHasta', N'Hasta:', N'To:', N'Até:'),
    (N'frmBitacora.lblTitulo', N'Bitácora del Sistema', N'System audit log', N'Log de auditoria do sistema'),
    (N'frmBitacora.lblUsuario', N'Usuario:', N'User:', N'Usuário:'),
    (N'frmConfirmarCierreMantenimiento', N'Cierre de mantenimiento', N'Maintenance closure', N'Fechamento de manutenção'),
    (N'frmConfirmarCierreMantenimiento.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmConfirmarCierreMantenimiento.btnConfirmarCierre', N'Confirmar cierre', N'Confirm closure', N'Confirmar fechamento'),
    (N'frmConfirmarCierreMantenimiento.lblTitulo', N'Registrar cierre de mantenimiento', N'Record maintenance closure', N'Registrar fechamento de manutenção'),
    (N'frmContraseña', N'Cambiar Contraseña', N'Change password', N'Alterar senha'),
    (N'frmContraseña.btnContinuar', N'Continuar', N'Continue', N'Continuar'),
    (N'frmContraseña.button1', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmContraseña.label1', N'Contraseña Actual:', N'Current password:', N'Senha atual:'),
    (N'frmContraseña.label2', N'Nueva Contraseña:', N'New password:', N'Nova senha:'),
    (N'frmContraseña.label3', N'Confirmar Contraseña:', N'Confirm password:', N'Confirmar senha:'),
    (N'frmContraseña.label4', N'- 6 o más caracteres' + CHAR(13) + CHAR(10) + N'- 1 o más letras MAYÚSCULAS' + CHAR(13) + CHAR(10) + N'- 1 o más NÚMEROS', N'- 6 or more characters' + CHAR(13) + CHAR(10) + N'- 1 or more UPPERCASE letters' + CHAR(13) + CHAR(10) + N'- 1 or more NUMBERS', N'- 6 ou mais caracteres' + CHAR(13) + CHAR(10) + N'- 1 ou mais letras MAIÚSCULAS' + CHAR(13) + CHAR(10) + N'- 1 ou mais NÚMEROS'),
    (N'frmCoordinarVisita', N'Coordinar visita técnica', N'Schedule technical visit', N'Agendar visita técnica'),
    (N'frmCoordinarVisita.btnBuscarAlternativo', N'Buscar alternativo', N'Find alternate', N'Buscar alternativo'),
    (N'frmCoordinarVisita.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmCoordinarVisita.btnConfirmar', N'Confirmar solicitud de visita', N'Confirm visit request', N'Confirmar solicitação de visita'),
    (N'frmCoordinarVisita.lblFecha', N'Fecha coordinada:', N'Scheduled date:', N'Data agendada:'),
    (N'frmCoordinarVisita.lblTecnico', N'Técnico: (seleccioná una alerta)', N'Technician: (select an alert)', N'Técnico: (selecione um alerta)'),
    (N'frmCoordinarVisita.lblTitulo', N'Coordinar visita técnica', N'Schedule technical visit', N'Agendar visita técnica'),
    (N'frmCubrirTurno', N'Cubrir turno', N'Cover shift', N'Cobrir turno'),
    (N'frmCubrirTurno.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmCubrirTurno.btnTomarTurno', N'Tomar este turno', N'Take this shift', N'Assumir este turno'),
    (N'frmCubrirTurno.lblTitulo', N'Turnos disponibles para cubrir', N'Shifts available to cover', N'Turnos disponíveis para cobrir'),
    (N'frmDashboard', N'Panel de indicadores', N'Dashboard', N'Painel de indicadores'),
    (N'frmDashboard.btnActualizar', N'Actualizar', N'Refresh', N'Atualizar'),
    (N'frmDashboard.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmDashboard.lblFranjaAsistencia', N'Franja a graficar:', N'Time slot to chart:', N'Faixa a exibir:'),
    (N'frmDashboard.lblTitulo', N'Panel de indicadores', N'Dashboard', N'Painel de indicadores'),
    (N'frmEditarUsuario', N'Editar datos', N'Edit details', N'Editar dados'),
    (N'frmEditarUsuario.btnAceptar', N'Guardar', N'Save', N'Salvar'),
    (N'frmEditarUsuario.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmEditarUsuario.lblApellido', N'Apellido:', N'Last name:', N'Sobrenome:'),
    (N'frmEditarUsuario.lblEmail', N'Email:', N'Email:', N'E-mail:'),
    (N'frmEditarUsuario.lblNombrePersona', N'Nombre:', N'First name:', N'Nome:'),
    (N'frmEditarUsuario.lblTelefono', N'Teléfono:', N'Phone:', N'Telefone:'),
    (N'frmEvaluarAutorizarVisita', N'Evaluar y autorizar visita', N'Evaluate and authorize visit', N'Avaliar e autorizar visita'),
    (N'frmEvaluarAutorizarVisita.btnAutorizar', N'Autorizar visita', N'Authorize visit', N'Autorizar visita'),
    (N'frmEvaluarAutorizarVisita.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmEvaluarAutorizarVisita.btnDescartar', N'Descartar alerta', N'Dismiss alert', N'Descartar alerta'),
    (N'frmEvaluarAutorizarVisita.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmEvaluarAutorizarVisita.lblTitulo', N'Evaluar y autorizar visita técnica', N'Evaluate and authorize technical visit', N'Avaliar e autorizar visita técnica'),
    (N'frmEvaluarCobertura', N'Evaluar cobertura', N'Evaluate coverage', N'Avaliar cobertura'),
    (N'frmEvaluarCobertura.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmEvaluarCobertura.btnEvaluar', N'Evaluar cobertura', N'Evaluate coverage', N'Avaliar cobertura'),
    (N'frmEvaluarCobertura.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmEvaluarCobertura.lblSemana', N'Semana a evaluar:', N'Week to evaluate:', N'Semana a avaliar:'),
    (N'frmEvaluarCobertura.lblTitulo', N'Evaluar cobertura del servicio', N'Evaluate service coverage', N'Avaliar cobertura do serviço'),
    (N'frmFicharAsistencia', N'Fichar asistencia', N'Clock in/out', N'Registrar ponto'),
    (N'frmFicharAsistencia.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmFicharAsistencia.btnEgreso', N'Registrar egreso', N'Clock out', N'Registrar saída'),
    (N'frmFicharAsistencia.btnIngreso', N'Registrar ingreso', N'Clock in', N'Registrar entrada'),
    (N'frmFicharAsistencia.lblTitulo', N'Fichar asistencia', N'Clock in/out', N'Registrar ponto'),
    (N'frmGenerarGrilla', N'Generar grilla de turnos', N'Generate shift schedule', N'Gerar escala de turnos'),
    (N'frmGenerarGrilla.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmGenerarGrilla.btnComunicar', N'Comunicar horarios', N'Communicate schedule', N'Comunicar horários'),
    (N'frmGenerarGrilla.btnConfirmar', N'Confirmar grilla', N'Confirm schedule', N'Confirmar escala'),
    (N'frmGenerarGrilla.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmGenerarGrilla.btnGenerar', N'Generar grilla', N'Generate schedule', N'Gerar escala'),
    (N'frmGenerarGrilla.lblSemana', N'Semana (lunes):', N'Week (Monday):', N'Semana (segunda-feira):'),
    (N'frmGenerarGrilla.lblTitulo', N'Generar grilla de turnos', N'Generate shift schedule', N'Gerar escala de turnos'),
    (N'frmGestionFranjas', N'Franjas horarias', N'Time slots', N'Faixas horárias'),
    (N'frmGestionFranjas.btnAgregar', N'Agregar', N'Add', N'Adicionar'),
    (N'frmGestionFranjas.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmGestionFranjas.btnEliminar', N'Eliminar seleccionada', N'Delete selected', N'Excluir selecionada'),
    (N'frmGestionFranjas.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmGestionFranjas.lblDia', N'Día:', N'Day:', N'Dia:'),
    (N'frmGestionFranjas.lblHoraFin', N'A:', N'To:', N'Até:'),
    (N'frmGestionFranjas.lblHoraInicio', N'De:', N'From:', N'De:'),
    (N'frmGestionFranjas.lblRol', N'Rol:', N'Role:', N'Função:'),
    (N'frmGestionFranjas.lblTitulo', N'Gestión de franjas horarias', N'Time slot management', N'Gestão de faixas horárias'),
    (N'frmHistorialUsuario', N'Historial de usuario', N'User history', N'Histórico do usuário'),
    (N'frmHistorialUsuario.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmHistorialUsuario.btnPaginaAnterior', N'< Anterior', N'< Previous', N'< Anterior'),
    (N'frmHistorialUsuario.btnPaginaSiguiente', N'Siguiente >', N'Next >', N'Próxima >'),
    (N'frmHistorialUsuario.btnRollback', N'Restaurar versión', N'Restore version', N'Restaurar versão'),
    (N'frmHistorialUsuario.lblTitulo', N'Historial de cambios', N'Change history', N'Histórico de alterações'),
    (N'frmIdiomas', N'Gestión de idiomas', N'Language management', N'Gestão de idiomas'),
    (N'frmIdiomas.btnAgregarIdioma', N'Agregar idioma', N'Add language', N'Adicionar idioma'),
    (N'frmIdiomas.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmIdiomas.btnEliminarIdioma', N'Eliminar idioma', N'Delete language', N'Excluir idioma'),
    (N'frmIdiomas.btnGuardarTraducciones', N'Guardar traducciones', N'Save translations', N'Salvar traduções'),
    (N'frmIdiomas.btnRenombrar', N'Renombrar idioma', N'Rename language', N'Renomear idioma'),
    (N'frmIdiomas.btnToggleHabilitado', N'Habilitar/Deshabilitar', N'Enable/Disable', N'Ativar/Desativar'),
    (N'frmIdiomas.lblIdiomas', N'Idiomas', N'Languages', N'Idiomas'),
    (N'frmIdiomas.lblTraducciones', N'Traducciones del idioma seleccionado', N'Translations of the selected language', N'Traduções do idioma selecionado'),
    (N'frmMantenimientoPredictivo', N'Mantenimiento predictivo', N'Predictive maintenance', N'Manutenção preditiva'),
    (N'frmMantenimientoPredictivo.btnActualizar', N'Actualizar', N'Refresh', N'Atualizar'),
    (N'frmMantenimientoPredictivo.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmMantenimientoPredictivo.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmMantenimientoPredictivo.lblTitulo', N'Mantenimiento predictivo', N'Predictive maintenance', N'Manutenção preditiva'),
    (N'frmMenu.administracionToolStripMenuItem', N'Administración', N'Administration', N'Administração'),
    (N'frmMenu.ajustarPorAusenciaToolStripMenuItem', N'Ajustar grilla por ausencia', N'Adjust schedule for absence', N'Ajustar escala por ausência'),
    (N'frmMenu.asistenciaToolStripMenuItem', N'Asistencia', N'Attendance', N'Presença'),
    (N'frmMenu.bitacoraToolStripMenuItem', N'Bitácora', N'Audit log', N'Log de auditoria'),
    (N'frmMenu.cambiarContraseñaToolStripMenuItem', N'Cambiar Contraseña', N'Change password', N'Alterar senha'),
    (N'frmMenu.cerrarSesionToolStripMenuItem', N'Cerrar sesión', N'Log out', N'Sair'),
    (N'frmMenu.configuraciónToolStripMenuItem', N'Configuración', N'Settings', N'Configurações'),
    (N'frmMenu.confirmarCierreToolStripMenuItem', N'Confirmar cierre de mantenimiento', N'Confirm maintenance closure', N'Confirmar fechamento de manutenção'),
    (N'frmMenu.coordinarVisitaToolStripMenuItem', N'Coordinar visita técnica', N'Schedule technical visit', N'Agendar visita técnica'),
    (N'frmMenu.cubrirTurnoToolStripMenuItem', N'Cubrir turno', N'Cover shift', N'Cobrir turno'),
    (N'frmMenu.disponibilidadToolStripMenuItem', N'Registrar disponibilidad', N'Record availability', N'Registrar disponibilidade'),
    (N'frmMenu.evaluarAutorizarToolStripMenuItem', N'Evaluar y autorizar visita', N'Evaluate and authorize visit', N'Avaliar e autorizar visita'),
    (N'frmMenu.evaluarCoberturaToolStripMenuItem', N'Evaluar cobertura del servicio', N'Evaluate service coverage', N'Avaliar cobertura do serviço'),
    (N'frmMenu.ficharAsistenciaToolStripMenuItem', N'Fichar asistencia', N'Clock in/out', N'Registrar ponto'),
    (N'frmMenu.generarGrillaToolStripMenuItem', N'Generar grilla de turnos', N'Generate shift schedule', N'Gerar escala de turnos'),
    (N'frmMenu.gestionFranjasToolStripMenuItem', N'Gestión de franjas horarias', N'Time slot management', N'Gestão de faixas horárias'),
    (N'frmMenu.horariosToolStripMenuItem', N'Horarios', N'Schedules', N'Horários'),
    (N'frmMenu.idiomasToolStripMenuItem', N'Gestión de idiomas', N'Language management', N'Gestão de idiomas'),
    (N'frmMenu.lblIdiomaStatus', N'Idioma:', N'Language:', N'Idioma:'),
    (N'frmMenu.mantenimientoPredictivoToolStripMenuItem', N'Mantenimiento predictivo', N'Predictive maintenance', N'Manutenção preditiva'),
    (N'frmMenu.mantenimientoToolStripMenuItem', N'Mantenimiento', N'Maintenance', N'Manutenção'),
    (N'frmMenu.misNotificacionesToolStripMenuItem', N'Mis notificaciones', N'My notifications', N'Minhas notificações'),
    (N'frmMenu.misTurnosToolStripMenuItem', N'Mis turnos', N'My shifts', N'Meus turnos'),
    (N'frmMenu.panelToolStripMenuItem', N'Panel', N'Dashboard', N'Painel'),
    (N'frmMenu.perfilesToolStripMenuItem', N'Roles y Permisos', N'Roles and permissions', N'Perfis e permissões'),
    (N'frmMenu.realizarRevisionToolStripMenuItem', N'Realizar revisión técnica', N'Perform technical inspection', N'Realizar revisão técnica'),
    (N'frmMenu.registrarAsistenciaSociosToolStripMenuItem', N'Registrar asistencia de socios', N'Record member attendance', N'Registrar presença de sócios'),
    (N'frmMenu.registrarUsoToolStripMenuItem', N'Registrar uso de máquina', N'Record machine usage', N'Registrar uso de máquina'),
    (N'frmMenu.simulacionSensoresToolStripMenuItem', N'Simular sensores IoT', N'Simulate IoT sensors', N'Simular sensores IoT'),
    (N'frmMenu.usuariosBloqueadosToolStripMenuItem', N'Gestión de usuarios', N'User management', N'Gestão de usuários'),
    (N'frmMenu.usuarioToolStripMenuItem', N'Usuario', N'User', N'Usuário'),
    (N'frmMenu_Titulo', N'Menú — {0}', N'Menu — {0}', N'Menu — {0}'),
    (N'frmMisNotificaciones', N'Mis notificaciones', N'My notifications', N'Minhas notificações'),
    (N'frmMisNotificaciones.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmMisNotificaciones.btnExportar', N'Exportar a Excel', N'Export to Excel', N'Exportar para Excel'),
    (N'frmMisNotificaciones.lblTitulo', N'Mis notificaciones', N'My notifications', N'Minhas notificações'),
    (N'frmMisTurnos', N'Mis turnos', N'My shifts', N'Meus turnos'),
    (N'frmMisTurnos.btnCancelarTurno', N'Cancelar turno', N'Cancel shift', N'Cancelar turno'),
    (N'frmMisTurnos.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmMisTurnos.lblTitulo', N'Mis turnos', N'My shifts', N'Meus turnos'),
    (N'frmNuevoUsuario', N'Nuevo usuario', N'New user', N'Novo usuário'),
    (N'frmNuevoUsuario.btnAceptar', N'Crear', N'Create', N'Criar'),
    (N'frmNuevoUsuario.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmNuevoUsuario.lblApellido', N'Apellido:', N'Last name:', N'Sobrenome:'),
    (N'frmNuevoUsuario.lblContrasena', N'Contraseña:', N'Password:', N'Senha:'),
    (N'frmNuevoUsuario.lblEmail', N'Email:', N'Email:', N'E-mail:'),
    (N'frmNuevoUsuario.lblNombre', N'Usuario:', N'Username:', N'Usuário:'),
    (N'frmNuevoUsuario.lblNombrePersona', N'Nombre:', N'First name:', N'Nome:'),
    (N'frmNuevoUsuario.lblRol', N'Rol:', N'Role:', N'Perfil:'),
    (N'frmNuevoUsuario.lblTelefono', N'Teléfono:', N'Phone:', N'Telefone:'),
    (N'frmPerfiles', N'Gestión de Roles y Permisos', N'Roles and permissions', N'Perfis e permissões'),
    (N'frmPerfiles.btnAgregarRol', N'Agregar Rol', N'Add role', N'Adicionar perfil'),
    (N'frmPerfiles.btnAsignarPadre', N'Asignar padre', N'Assign parent', N'Atribuir pai'),
    (N'frmPerfiles.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmPerfiles.btnDuplicarRol', N'Duplicar rol', N'Duplicate role', N'Duplicar perfil'),
    (N'frmPerfiles.btnEliminar', N'Eliminar', N'Delete', N'Excluir'),
    (N'frmPerfiles.btnGuardarPermisos', N'Guardar permisos', N'Save permissions', N'Salvar permissões'),
    (N'frmPerfiles.lblPadre', N'Rol padre:', N'Parent role:', N'Perfil pai:'),
    (N'frmPerfiles.lblPermisos', N'Permisos del rol:', N'Role permissions:', N'Permissões do perfil:'),
    (N'frmPerfiles.lblSeleccionado', N'Seleccioná un nodo:', N'Select a node:', N'Selecione um nó:'),
    (N'frmRealizarRevision', N'Revisión técnica', N'Technical inspection', N'Revisão técnica'),
    (N'frmRealizarRevision.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmRealizarRevision.btnRegistrarInforme', N'Registrar informe', N'Record report', N'Registrar relatório'),
    (N'frmRealizarRevision.chkPendienteRepuesto', N'Requiere repuesto no disponible', N'Requires an unavailable spare part', N'Requer peça indisponível'),
    (N'frmRealizarRevision.lblEquipo', N'Equipo: —', N'Equipment: —', N'Equipamento: —'),
    (N'frmRealizarRevision.lblResultado', N'Resultado de la revisión:', N'Inspection result:', N'Resultado da revisão:'),
    (N'frmRealizarRevision.lblTitulo', N'Realizar revisión y emitir informe', N'Perform inspection and issue report', N'Realizar revisão e emitir relatório'),
    (N'frmRegistrarAsistenciaSocios', N'Asistencia de socios', N'Member attendance', N'Presença de sócios'),
    (N'frmRegistrarAsistenciaSocios.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmRegistrarAsistenciaSocios.btnRegistrar', N'Registrar', N'Record', N'Registrar'),
    (N'frmRegistrarAsistenciaSocios.lblCantidad', N'Cantidad de socios:', N'Number of members:', N'Quantidade de sócios:'),
    (N'frmRegistrarAsistenciaSocios.lblFecha', N'Fecha:', N'Date:', N'Data:'),
    (N'frmRegistrarAsistenciaSocios.lblFranja', N'Franja:', N'Time slot:', N'Faixa:'),
    (N'frmRegistrarAsistenciaSocios.lblTitulo', N'Registrar asistencia de socios', N'Record member attendance', N'Registrar presença de sócios'),
    (N'frmRegistrarDisponibilidad', N'Disponibilidad horaria', N'Availability', N'Disponibilidade'),
    (N'frmRegistrarDisponibilidad.btnAceptar', N'Aceptar', N'OK', N'OK'),
    (N'frmRegistrarDisponibilidad.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmRegistrarDisponibilidad.lblTitulo', N'Registrar disponibilidad horaria', N'Record time availability', N'Registrar disponibilidade de horários'),
    (N'frmRegistrarUsoMaquina', N'Uso de máquina', N'Machine usage', N'Uso de máquina'),
    (N'frmRegistrarUsoMaquina.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmRegistrarUsoMaquina.btnRegistrar', N'Registrar uso', N'Record usage', N'Registrar uso'),
    (N'frmRegistrarUsoMaquina.lblEquipo', N'Equipo:', N'Equipment:', N'Equipamento:'),
    (N'frmRegistrarUsoMaquina.lblTitulo', N'Registrar uso de la máquina', N'Record machine usage', N'Registrar uso da máquina'),
    (N'frmRestaurarIntegridad', N'Error de integridad', N'Integrity error', N'Erro de integridade'),
    (N'frmRestaurarIntegridad.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmRestaurarIntegridad.btnRecalcular', N'Recalcular y continuar', N'Recalculate and continue', N'Recalcular e continuar'),
    (N'frmRestaurarIntegridad.btnRestaurar', N'Restaurar desde historial', N'Restore from history', N'Restaurar a partir do histórico'),
    (N'frmRestaurarIntegridad.lblTitulo', N'Se detectaron problemas de integridad en la base de datos:', N'Integrity problems were detected in the database:', N'Foram detectados problemas de integridade no banco de dados:'),
    (N'frmSeleccionarReemplazo', N'Seleccionar reemplazo', N'Select replacement', N'Selecionar substituto'),
    (N'frmSeleccionarReemplazo.btnAsignar', N'Asignar', N'Assign', N'Atribuir'),
    (N'frmSeleccionarReemplazo.btnCancelar', N'Cancelar', N'Cancel', N'Cancelar'),
    (N'frmSeleccionarReemplazo.lblTitulo', N'Elegir empleado de reemplazo', N'Choose a replacement employee', N'Escolha o funcionário substituto'),
    (N'frmSimulacionSensores', N'Simulación de sensores IoT', N'IoT sensor simulation', N'Simulação de sensores IoT'),
    (N'frmSimulacionSensores.btnCerrar', N'Cerrar', N'Close', N'Fechar'),
    (N'frmSimulacionSensores.btnDetenerApi', N'Detener API', N'Stop API', N'Parar API'),
    (N'frmSimulacionSensores.btnDetenerSimulacion', N'Detener simulación', N'Stop simulation', N'Parar simulação'),
    (N'frmSimulacionSensores.btnIniciarApi', N'Iniciar API', N'Start API', N'Iniciar API'),
    (N'frmSimulacionSensores.btnIniciarSimulacion', N'Iniciar simulación', N'Start simulation', N'Iniciar simulação'),
    (N'frmSimulacionSensores.lblIntervalo', N'Intervalo entre eventos (s):', N'Interval between events (s):', N'Intervalo entre eventos (s):'),
    (N'frmSimulacionSensores.lblTitulo', N'Simulación de sensores IoT', N'IoT sensor simulation', N'Simulação de sensores IoT'),
    (N'LogIn', N'Iniciar Sesión', N'Log in', N'Entrar'),
    (N'LogIn.btnIngresar', N'Ingresar', N'Log in', N'Entrar'),
    (N'LogIn.lblContrasena', N'Contraseña', N'Password', N'Senha'),
    (N'LogIn.lblUsuario', N'Usuario', N'Username', N'Usuário'),
    (N'btnmsg_Aceptar', N'Aceptar', N'OK', N'OK'),
    (N'btnmsg_No', N'No', N'No', N'Não'),
    (N'btnmsg_Si', N'Sí', N'Yes', N'Sim'),
    (N'chart_AsistenciaDeSocios', N'Asistencia de socios en el tiempo (Proceso 3)', N'Member attendance over time (Process 3)', N'Presença de sócios ao longo do tempo (Processo 3)'),
    (N'chart_CantidadDeFranjas', N'Cantidad de franjas', N'Number of time slots', N'Quantidade de faixas'),
    (N'chart_EvaluacionCobertura', N'Evaluación de cobertura (Proceso 1 + 3)', N'Coverage evaluation (Process 1 + 3)', N'Avaliação de cobertura (Processo 1 + 3)'),
    (N'chart_Socios', N'Socios', N'Members', N'Sócios'),
    (N'chart_UmbralCritico', N'Umbral crítico', N'Critical threshold', N'Limite crítico'),
    (N'chart_UsoAcumulado', N'Uso acumulado', N'Accumulated usage', N'Uso acumulado'),
    (N'chart_UsoAcumuladoPorEquipo', N'Uso acumulado por equipo (Proceso 2)', N'Accumulated usage per equipment (Process 2)', N'Uso acumulado por equipamento (Processo 2)'),
    (N'colhdr_Accion', N'Acción', N'Action', N'Ação'),
    (N'colhdr_Apellido', N'Apellido', N'Last name', N'Sobrenome'),
    (N'colhdr_Bloqueado', N'Bloqueado', N'Locked', N'Bloqueado'),
    (N'colhdr_Clave', N'Clave', N'Key', N'Chave'),
    (N'colhdr_Email', N'Email', N'Email', N'E-mail'),
    (N'colhdr_Fecha', N'Fecha y Hora', N'Date and time', N'Data e hora'),
    (N'colhdr_FechaCambio', N'Fecha', N'Date', N'Data'),
    (N'colhdr_Habilitado', N'Habilitado', N'Enabled', N'Ativado'),
    (N'colhdr_Id', N'ID', N'ID', N'ID'),
    (N'colhdr_IntentosFallidos', N'Intentos', N'Attempts', N'Tentativas'),
    (N'colhdr_Nombre', N'Idioma', N'Language', N'Idioma'),
    (N'colhdr_NombrePersona', N'Nombre', N'First name', N'Nome'),
    (N'colhdr_Perfiles', N'Perfiles', N'Roles', N'Perfis'),
    (N'colhdr_RealizadoPor', N'Realizado por', N'Performed by', N'Realizado por'),
    (N'colhdr_Rol', N'Rol', N'Role', N'Perfil'),
    (N'colhdr_Telefono', N'Teléfono', N'Phone', N'Telefone'),
    (N'colhdr_TextoDefault', N'Texto por defecto', N'Default text', N'Texto padrão'),
    (N'colhdr_TextoTraduccion', N'Traducción', N'Translation', N'Tradução'),
    (N'colhdr_TipoCambio', N'Tipo', N'Type', N'Tipo'),
    (N'colhdr_Usuario', N'Usuario', N'User', N'Usuário'),
    (N'colhdr_VersionOrigen', N'Versión origen', N'Source version', N'Versão de origem'),
    (N'hdr_Alerta', N'Alerta', N'Alert', N'Alerta'),
    (N'hdr_Dia', N'Día', N'Day', N'Dia'),
    (N'hdr_DiasEstimadosRestantes', N'Días estimados restantes', N'Estimated days remaining', N'Dias estimados restantes'),
    (N'hdr_Empleado', N'Empleado', N'Employee', N'Funcionário'),
    (N'hdr_Equipo', N'Equipo', N'Equipment', N'Equipamento'),
    (N'hdr_Estado', N'Estado', N'Status', N'Estado'),
    (N'hdr_Fecha', N'Fecha', N'Date', N'Data'),
    (N'hdr_FechaAlerta', N'Fecha alerta', N'Alert date', N'Data do alerta'),
    (N'hdr_FechaCoordinada', N'Fecha coordinada', N'Scheduled date', N'Data agendada'),
    (N'hdr_FechaDelInforme', N'Fecha del informe', N'Report date', N'Data do relatório'),
    (N'hdr_Franja', N'Franja', N'Time slot', N'Faixa'),
    (N'hdr_HoraFin', N'Hora fin', N'End time', N'Hora de término'),
    (N'hdr_HoraInicio', N'Hora inicio', N'Start time', N'Hora de início'),
    (N'hdr_Horario', N'Horario', N'Time', N'Horário'),
    (N'hdr_Mensaje', N'Mensaje', N'Message', N'Mensagem'),
    (N'hdr_PersonalAsignado', N'Personal asignado', N'Assigned staff', N'Pessoal atribuído'),
    (N'hdr_RepuestoPendiente', N'¿Repuesto pendiente?', N'Spare part pending?', N'Peça pendente?'),
    (N'hdr_Resultado', N'Resultado', N'Result', N'Resultado'),
    (N'hdr_Rol', N'Rol', N'Role', N'Função'),
    (N'hdr_SociosAsistidos', N'Socios asistidos', N'Members attended', N'Sócios presentes'),
    (N'hdr_UmbralCritico', N'Umbral crítico', N'Critical threshold', N'Limite crítico'),
    (N'hdr_Urgencia', N'Urgencia', N'Urgency', N'Urgência'),
    (N'hdr_UsoAcumulado', N'Uso acumulado', N'Accumulated usage', N'Uso acumulado'),
    (N'input_AgregarIdioma', N'Agregar idioma', N'Add language', N'Adicionar idioma'),
    (N'input_AgregarRol', N'Agregar Rol', N'Add role', N'Adicionar perfil'),
    (N'input_DuplicarRol', N'Duplicar rol', N'Duplicate role', N'Duplicar perfil'),
    (N'input_NombreDelNuevoIdioma', N'Nombre del nuevo idioma:', N'Name of the new language:', N'Nome do novo idioma:'),
    (N'input_NombreDelNuevoRol', N'Nombre del nuevo rol:', N'Name of the new role:', N'Nome do novo perfil:'),
    (N'input_NombreDelRol', N'Nombre del rol:', N'Role name:', N'Nome do perfil:'),
    (N'input_NuevoNombre', N'Nuevo nombre:', N'New name:', N'Novo nome:'),
    (N'input_RenombrarIdioma', N'Renombrar idioma', N'Rename language', N'Renomear idioma'),
    (N'input_SufijoCopia', N'{0} (copia)', N'{0} (copy)', N'{0} (cópia)'),
    (N'lbl_DetalleEquipo', N'Equipo: {0}  |  Estado actual: {1}  |  Uso acumulado: {2}', N'Equipment: {0}  |  Current status: {1}  |  Accumulated usage: {2}', N'Equipamento: {0}  |  Estado atual: {1}  |  Uso acumulado: {2}'),
    (N'lbl_DisponibilidadYaCargada', N'Ya habías cargado disponibilidad para esta semana — podés modificarla.', N'You had already entered availability for this week — you can change it.', N'Você já havia registrado disponibilidade para esta semana — pode alterá-la.'),
    (N'lbl_EquipoConUso', N'Equipo: {0}  (uso acumulado: {1})', N'Equipment: {0}  (accumulated usage: {1})', N'Equipamento: {0}  (uso acumulado: {1})'),
    (N'lbl_EquipoSinDetalle', N'Equipo: (no se pudo obtener el detalle)', N'Equipment: (details could not be retrieved)', N'Equipamento: (não foi possível obter os detalhes)'),
    (N'lbl_EquipoSinSeleccion', N'Equipo: —', N'Equipment: —', N'Equipamento: —'),
    (N'lbl_Idioma', N'Idioma: ', N'Language: ', N'Idioma: '),
    (N'lbl_IngresoAbiertoHoy', N'Tenés un ingreso registrado hoy, sin egreso.', N'You have a clock-in today without a clock-out.', N'Você tem uma entrada registrada hoje, sem saída.'),
    (N'lbl_PaginaDe', N'Página {0} de {1}', N'Page {0} of {1}', N'Página {0} de {1}'),
    (N'lbl_PermisoSeleccionado', N'Permiso: {0}', N'Permission: {0}', N'Permissão: {0}'),
    (N'lbl_RolSeleccionado', N'Rol: {0}', N'Role: {0}', N'Perfil: {0}'),
    (N'lbl_SinEmpleadosParaFranja', N'No hay empleados disponibles para esta franja.', N'There are no employees available for this time slot.', N'Não há funcionários disponíveis para esta faixa.'),
    (N'lbl_SinIngresoAbiertoHoy', N'No tenés ningún ingreso abierto hoy.', N'You have no open clock-in today.', N'Você não tem nenhuma entrada aberta hoje.'),
    (N'lbl_SinTecnicoHabitual', N'Sin técnico habitual asignado — usá ''Buscar alternativo''.', N'No usual technician assigned — use ''Find alternate''.', N'Sem técnico habitual atribuído — use ''Buscar alternativo''.'),
    (N'lbl_TecnicoAlternativo', N'Técnico (alternativo): {0}', N'Technician (alternate): {0}', N'Técnico (alternativo): {0}'),
    (N'lbl_TecnicoHabitual', N'Técnico habitual: {0}', N'Usual technician: {0}', N'Técnico habitual: {0}'),
    (N'lbl_TecnicoSinAlerta', N'Técnico: (seleccioná una alerta)', N'Technician: (select an alert)', N'Técnico: (selecione um alerta)'),
    (N'lbl_UsuarioNombre', N'Usuario: {0}', N'User: {0}', N'Usuário: {0}'),
    (N'msg_AlertaDescartada', N'Alerta descartada.', N'Alert dismissed.', N'Alerta descartado.'),
    (N'msg_AsignacionesGuardadas', N'Asignaciones guardadas.', N'Assignments saved.', N'Atribuições salvas.'),
    (N'msg_AsistenciaDeSociosRegistrada', N'Asistencia de socios registrada.', N'Member attendance recorded.', N'Presença de sócios registrada.'),
    (N'msg_AutorizarLaVisitaTecnicaPara', N'¿Autorizar la visita técnica para ''{0}''?', N'Authorize the technical visit for ''{0}''?', N'Autorizar a visita técnica para ''{0}''?'),
    (N'msg_AvisoUnaAusenciaParaEsteTurno', N'¿{0} {1} avisó una ausencia para este turno?', N'Did {0} {1} report an absence for this shift?', N'{0} {1} avisou uma ausência para este turno?'),
    (N'msg_Bienvenido', N'Bienvenido, {0}!', N'Welcome, {0}!', N'Bem-vindo, {0}!'),
    (N'msg_CierreConfirmadoEquipoOperativo', N'Cierre confirmado. Equipo operativo con el contador reiniciado.', N'Closure confirmed. Equipment operational with the counter reset.', N'Fechamento confirmado. Equipamento operacional com o contador reiniciado.'),
    (N'msg_CompletaTodosLosCampos', N'Completá todos los campos.', N'Fill in all the fields.', N'Preencha todos os campos.'),
    (N'msg_CompletaUsuarioYContrasena', N'Completá usuario y contraseña.', N'Enter username and password.', N'Preencha usuário e senha.'),
    (N'msg_ConfirmarCancelarTurno', N'¿Seguro que querés cancelar el turno del {0} {1}?' + CHAR(10) + N'Se va a notificar automáticamente al administrador y a los empleados disponibles para cubrirlo.', N'Are you sure you want to cancel the shift on {0} {1}?' + CHAR(10) + N'The administrator and the employees available to cover it will be notified automatically.', N'Tem certeza de que deseja cancelar o turno de {0} {1}?' + CHAR(10) + N'O administrador e os funcionários disponíveis para cobri-lo serão notificados automaticamente.'),
    (N'msg_ConfirmarCierre', N'¿Confirmar el cierre? Se reiniciará el contador de uso y el equipo quedará operativo.', N'Confirm the closure? The usage counter will be reset and the equipment will be operational.', N'Confirmar o fechamento? O contador de uso será reiniciado e o equipamento ficará operacional.'),
    (N'msg_ConfirmarCierreConRepuestoPendiente', N'Este informe indica que falta un repuesto. El equipo quedará marcado ''En mantenimiento'' y NO se reiniciará el contador de uso. ¿Confirmar de todas formas?', N'This report indicates a missing spare part. The equipment will be marked ''Under maintenance'' and the usage counter will NOT be reset. Confirm anyway?', N'Este relatório indica que falta uma peça. O equipamento ficará marcado ''Em manutenção'' e o contador de uso NÃO será reiniciado. Confirmar mesmo assim?'),
    (N'msg_ConfirmarRollback', N'¿Restaurar el estado del usuario ''{0}'' a la versión del {1:dd/MM/yyyy HH:mm}?' + CHAR(10) + CHAR(10) + N'Tipo de cambio registrado: {2}' + CHAR(10) + CHAR(10) + N'Nota: la contraseña NO se restaurará (se mantendrá la actual).', N'Restore user ''{0}'' to the version from {1:dd/MM/yyyy HH:mm}?' + CHAR(10) + CHAR(10) + N'Recorded change type: {2}' + CHAR(10) + CHAR(10) + N'Note: the password will NOT be restored (the current one is kept).', N'Restaurar o usuário ''{0}'' para a versão de {1:dd/MM/yyyy HH:mm}?' + CHAR(10) + CHAR(10) + N'Tipo de alteração registrado: {2}' + CHAR(10) + CHAR(10) + N'Observação: a senha NÃO será restaurada (a atual será mantida).'),
    (N'msg_ContrasenaCambiadaExitosamente', N'Contraseña cambiada exitosamente.', N'Password changed successfully.', N'Senha alterada com sucesso.'),
    (N'msg_DesbloquearAlUsuario', N'¿Desbloquear al usuario ''{0}''?', N'Unlock user ''{0}''?', N'Desbloquear o usuário ''{0}''?'),
    (N'msg_DescartarEstaAlertaComoFalsoPositivo', N'¿Descartar esta alerta como falso positivo?', N'Dismiss this alert as a false positive?', N'Descartar este alerta como falso positivo?'),
    (N'msg_DisponibilidadRegistradaCorrectamente', N'Disponibilidad registrada correctamente.', N'Availability recorded successfully.', N'Disponibilidade registrada com sucesso.'),
    (N'msg_EgresoRegistradoALas', N'Egreso registrado a las {0:HH:mm}.', N'Clock-out recorded at {0:HH:mm}.', N'Saída registrada às {0:HH:mm}.'),
    (N'msg_ElegiUnTecnicoHabitualOAlternativoAntesDeConfirmar', N'Elegí un técnico (habitual o alternativo) antes de confirmar.', N'Choose a technician (usual or alternate) before confirming.', N'Escolha um técnico (habitual ou alternativo) antes de confirmar.'),
    (N'msg_EliminarAlUsuarioEstaAccionNoSePuedeDeshacer', N'¿Eliminar al usuario ''{0}''? Esta acción no se puede deshacer.', N'Delete user ''{0}''? This action cannot be undone.', N'Excluir o usuário ''{0}''? Esta ação não pode ser desfeita.'),
    (N'msg_EliminarElIdiomaSeBorraranTodasSusTraducciones', N'¿Eliminar el idioma ''{0}''? Se borrarán todas sus traducciones.', N'Delete language ''{0}''? All its translations will be deleted.', N'Excluir o idioma ''{0}''? Todas as suas traduções serão apagadas.'),
    (N'msg_EliminarElRolYTodosSusSubroles', N'¿Eliminar el rol ''{0}'' y todos sus sub-roles?', N'Delete role ''{0}'' and all its sub-roles?', N'Excluir o perfil ''{0}'' e todos os seus subperfis?'),
    (N'msg_EliminarLaFranja', N'¿Eliminar la franja ''{0} {1:hh\:mm}-{2:hh\:mm} ({3})''?', N'Delete time slot ''{0} {1:hh\:mm}-{2:hh\:mm} ({3})''?', N'Excluir a faixa ''{0} {1:hh\:mm}-{2:hh\:mm} ({3})''?'),
    (N'msg_ElNombreDeUsuarioYaExiste', N'El nombre de usuario ya existe.', N'The username already exists.', N'O nome de usuário já existe.'),
    (N'msg_ElSistemaNoPuedeIniciarse', N'El sistema no puede iniciarse debido a un problema interno.' + CHAR(10) + CHAR(10) + N'Comuníquese con el administrador del sistema.', N'The system cannot start due to an internal problem.' + CHAR(10) + CHAR(10) + N'Please contact the system administrator.', N'O sistema não pode ser iniciado devido a um problema interno.' + CHAR(10) + CHAR(10) + N'Entre em contato com o administrador do sistema.'),
    (N'msg_ElUsuarioNoEstaBloqueado', N'El usuario no está bloqueado.', N'The user is not locked.', N'O usuário não está bloqueado.'),
    (N'msg_EquipoMarcadoEnMantenimiento', N'Equipo marcado como ''En mantenimiento''.', N'Equipment marked as ''Under maintenance''.', N'Equipamento marcado como ''Em manutenção''.'),
    (N'msg_EquipoSinUmbralConfigurado', N'El equipo ''{0}'' no tiene un nivel de uso crítico configurado.' + CHAR(10) + N'Se notificará al Administrador para que lo defina.', N'Equipment ''{0}'' has no critical usage level configured.' + CHAR(10) + N'The Administrator will be notified to set it.', N'O equipamento ''{0}'' não tem um nível de uso crítico configurado.' + CHAR(10) + N'O Administrador será notificado para defini-lo.'),
    (N'msg_ErrorAlCambiarLaContrasena', N'Error al cambiar la contraseña.', N'Error changing the password.', N'Erro ao alterar a senha.'),
    (N'msg_EstadoRestauradoCorrectamente', N'Estado restaurado correctamente.', N'State restored successfully.', N'Estado restaurado com sucesso.'),
    (N'msg_EsteTurnoNoTieneUnEmpleadoAsignadoParaReemplazar', N'Este turno no tiene un empleado asignado para reemplazar.', N'This shift has no assigned employee to replace.', N'Este turno não tem um funcionário atribuído para substituir.'),
    (N'msg_EsteTurnoYaNoEstaAsignadoPuedeQueYaLoHayasCanceladoAntes', N'Este turno ya no está asignado (puede que ya lo hayas cancelado antes).', N'This shift is no longer assigned (you may have already cancelled it).', N'Este turno não está mais atribuído (talvez você já o tenha cancelado).'),
    (N'msg_EvaluacionDeCoberturaRegistradaSeUsaraParaAjustarLaProximaPl', N'Evaluación de cobertura registrada. Se usará para ajustar la próxima planificación.', N'Coverage evaluation recorded. It will be used to adjust the next schedule.', N'Avaliação de cobertura registrada. Será usada para ajustar o próximo planejamento.'),
    (N'msg_ExportacionCompletada', N'Exportación completada.', N'Export completed.', N'Exportação concluída.'),
    (N'msg_FranjaAgregada', N'Franja agregada.', N'Time slot added.', N'Faixa adicionada.'),
    (N'msg_FranjaEliminada', N'Franja eliminada.', N'Time slot deleted.', N'Faixa excluída.'),
    (N'msg_GenerarLaGrillaParaLaSemanaDel', N'¿Generar la grilla para la semana del {0:dd/MM}?', N'Generate the schedule for the week of {0:dd/MM}?', N'Gerar a escala para a semana de {0:dd/MM}?'),
    (N'msg_GrillaConfirmadaCorrectamente', N'Grilla confirmada correctamente.', N'Schedule confirmed successfully.', N'Escala confirmada com sucesso.'),
    (N'msg_HorariosComunicadosAlEquipo', N'Horarios comunicados al equipo.', N'Schedule communicated to the team.', N'Horários comunicados à equipe.'),
    (N'msg_InformeDeMantenimientoRegistradoSeNotificoAlAdministrador', N'Informe de mantenimiento registrado. Se notificó al Administrador.', N'Maintenance report recorded. The Administrator was notified.', N'Relatório de manutenção registrado. O Administrador foi notificado.'),
    (N'msg_IngresaElResultadoDeLaRevision', N'Ingresá el resultado de la revisión.', N'Enter the inspection result.', N'Informe o resultado da revisão.'),
    (N'msg_IngresaUnaCantidadValidaDeSocios', N'Ingresá una cantidad válida de socios.', N'Enter a valid number of members.', N'Informe uma quantidade válida de sócios.'),
    (N'msg_IngresaUnaContrasena', N'Ingresá una contraseña.', N'Enter a password.', N'Informe uma senha.'),
    (N'msg_IngresaUnNombreDeUsuario', N'Ingresá un nombre de usuario.', N'Enter a username.', N'Informe um nome de usuário.'),
    (N'msg_IngresoRegistradoALas', N'Ingreso registrado a las {0:HH:mm}.', N'Clock-in recorded at {0:HH:mm}.', N'Entrada registrada às {0:HH:mm}.'),
    (N'msg_LaContrasenaActualEsIncorrecta', N'La contraseña actual es incorrecta.', N'The current password is incorrect.', N'A senha atual está incorreta.'),
    (N'msg_LaGrillaDeEsaSemanaTodaviaNoEstaConfirmada', N'La grilla de esa semana todavía no está confirmada.', N'That week''s schedule is not confirmed yet.', N'A escala dessa semana ainda não está confirmada.'),
    (N'msg_LaGrillaYaFueConfirmadaNoSePuedeModificar', N'La grilla ya fue confirmada, no se puede modificar.', N'The schedule has already been confirmed and cannot be modified.', N'A escala já foi confirmada e não pode ser modificada.'),
    (N'msg_LasContrasenasNoCoinciden', N'Las contraseñas no coinciden.', N'Passwords do not match.', N'As senhas não coincidem.'),
    (N'msg_ListoElTurnoQuedoAsignadoAVos', N'¡Listo! El turno quedó asignado a vos.', N'Done! The shift is now assigned to you.', N'Pronto! O turno foi atribuído a você.'),
    (N'msg_LosPermisosDelCatalogoNoSePuedenEliminarDesasignaloUsandoLos', N'Los permisos del catálogo no se pueden eliminar.' + CHAR(10) + N'Desasignalo usando los checkboxes.', N'Catalog permissions cannot be deleted.' + CHAR(10) + N'Unassign it using the checkboxes.', N'As permissões do catálogo não podem ser excluídas.' + CHAR(10) + N'Desatribua-a usando as caixas de seleção.'),
    (N'msg_MarcarEstaFranjaComoDeficitDeCobertura', N'¿Marcar esta franja como déficit de cobertura?', N'Mark this time slot as a coverage shortfall?', N'Marcar esta faixa como déficit de cobertura?'),
    (N'msg_NoHayDatosParaExportar', N'No hay datos para exportar.', N'There is no data to export.', N'Não há dados para exportar.'),
    (N'msg_NoHayNingunaGrillaGeneradaParaEsaSemana', N'No hay ninguna grilla generada para esa semana.', N'No schedule has been generated for that week.', N'Nenhuma escala foi gerada para essa semana.'),
    (N'msg_NoHayTecnicosAlternativosRegistradosEnElSistema', N'No hay técnicos alternativos registrados en el sistema.', N'There are no alternate technicians registered in the system.', N'Não há técnicos alternativos cadastrados no sistema.'),
    (N'msg_NoHayUnaGrillaConfirmadaParaEsaSemanaONoTieneTurnosAsignados', N'No hay una grilla confirmada para esa semana, o no tiene turnos asignados.', N'There is no confirmed schedule for that week, or it has no assigned shifts.', N'Não há escala confirmada para essa semana, ou ela não tem turnos atribuídos.'),
    (N'msg_NoPodesEliminarTuPropioUsuario', N'No podés eliminar tu propio usuario.', N'You cannot delete your own user.', N'Você não pode excluir seu próprio usuário.'),
    (N'msg_NoSePudoExportar', N'No se pudo exportar: {0}', N'Could not export: {0}', N'Não foi possível exportar: {0}'),
    (N'msg_NoSePudoIniciarLaApi', N'No se pudo iniciar la API: {0}', N'Could not start the API: {0}', N'Não foi possível iniciar a API: {0}'),
    (N'msg_NoSePuedeEliminarElIdiomaPredeterminadoDelSistema', N'No se puede eliminar el idioma predeterminado del sistema.', N'The system''s default language cannot be deleted.', N'O idioma padrão do sistema não pode ser excluído.'),
    (N'msg_NoSePuedeEliminarUnIdiomaQueEstaEnUsoPorAlgunUsuario', N'No se puede eliminar un idioma que está en uso por algún usuario.', N'A language that is in use by a user cannot be deleted.', N'Um idioma em uso por algum usuário não pode ser excluído.'),
    (N'msg_NoSePuedeEliminarYaTieneDisponibilidadTurnosOHistorialAsocia', N'No se puede eliminar: ya tiene disponibilidad, turnos, o historial asociado.', N'Cannot delete: it already has associated availability, shifts or history.', N'Não é possível excluir: já possui disponibilidade, turnos ou histórico associados.'),
    (N'msg_NoSePuedeRestaurarUnaVersionQueYaEsUnRollback', N'No se puede restaurar una versión que ya es un rollback.', N'A version that is already a rollback cannot be restored.', N'Não é possível restaurar uma versão que já é um rollback.'),
    (N'msg_NoTenesPermisoParaAccederAEstaFuncion', N'No tenés permiso para acceder a esta función.', N'You do not have permission to access this feature.', N'Você não tem permissão para acessar esta função.'),
    (N'msg_NoTenesUnIngresoRegistradoHoyRegistraElIngresoPrimero', N'No tenés un ingreso registrado hoy. Registrá el ingreso primero.', N'You have no clock-in recorded today. Record the clock-in first.', N'Você não tem uma entrada registrada hoje. Registre a entrada primeiro.'),
    (N'msg_RegistroDeUsoGuardadoCorrectamente', N'Registro de uso guardado correctamente.', N'Usage record saved successfully.', N'Registro de uso salvo com sucesso.'),
    (N'msg_SeleccionaDiaYRol', N'Seleccioná día y rol.', N'Select day and role.', N'Selecione dia e função.'),
    (N'msg_SeleccionaUnaAlerta', N'Seleccioná una alerta.', N'Select an alert.', N'Selecione um alerta.'),
    (N'msg_SeleccionaUnaFranja', N'Seleccioná una franja.', N'Select a time slot.', N'Selecione uma faixa.'),
    (N'msg_SeleccionaUnaVisita', N'Seleccioná una visita.', N'Select a visit.', N'Selecione uma visita.'),
    (N'msg_SeleccionaUnEmpleado', N'Seleccioná un empleado.', N'Select an employee.', N'Selecione um funcionário.'),
    (N'msg_SeleccionaUnEquipo', N'Seleccioná un equipo.', N'Select a piece of equipment.', N'Selecione um equipamento.'),
    (N'msg_SeleccionaUnIdioma', N'Seleccioná un idioma.', N'Select a language.', N'Selecione um idioma.'),
    (N'msg_SeleccionaUnInforme', N'Seleccioná un informe.', N'Select a report.', N'Selecione um relatório.'),
    (N'msg_SeleccionaUnRol', N'Seleccioná un rol.', N'Select a role.', N'Selecione um perfil.'),
    (N'msg_SeleccionaUnTurnoDeLaLista', N'Seleccioná un turno de la lista.', N'Select a shift from the list.', N'Selecione um turno da lista.'),
    (N'msg_SeleccionaUnUsuario', N'Seleccioná un usuario.', N'Select a user.', N'Selecione um usuário.'),
    (N'msg_SinCompatiblesTurnoMarcadoSinCobertura', N'No hay ningún empleado disponible compatible con el rol y la franja.' + CHAR(10) + N'El turno queda marcado como sin cobertura.', N'No available employee matches the role and time slot.' + CHAR(10) + N'The shift is marked as uncovered.', N'Não há nenhum funcionário disponível compatível com a função e a faixa.' + CHAR(10) + N'O turno fica marcado como sem cobertura.'),
    (N'msg_SinCompatiblesTurnoSigueSinCobertura', N'No hay ningún empleado disponible compatible con el rol y la franja.' + CHAR(10) + N'El turno sigue sin cobertura.', N'No available employee matches the role and time slot.' + CHAR(10) + N'The shift remains uncovered.', N'Não há nenhum funcionário disponível compatível com a função e a faixa.' + CHAR(10) + N'O turno continua sem cobertura.'),
    (N'msg_SinConexionAbrirConfigurador', N'No se pudo conectar a la base de datos.' + CHAR(10) + CHAR(10) + N'¿Querés abrir el configurador para crearla o elegir otro servidor?', N'Could not connect to the database.' + CHAR(10) + CHAR(10) + N'Do you want to open the configuration tool to create it or choose another server?', N'Não foi possível conectar ao banco de dados.' + CHAR(10) + CHAR(10) + N'Deseja abrir o configurador para criá-lo ou escolher outro servidor?'),
    (N'msg_SinConexionSinConfigurador', N'No se pudo conectar a la base de datos y no se encontró el configurador (ConfiguradorBD.exe).' + CHAR(10) + CHAR(10) + N'Revisá la cadena de conexión en CAPAS.exe.config.', N'Could not connect to the database and the configuration tool (ConfiguradorBD.exe) was not found.' + CHAR(10) + CHAR(10) + N'Check the connection string in CAPAS.exe.config.', N'Não foi possível conectar ao banco de dados e o configurador (ConfiguradorBD.exe) não foi encontrado.' + CHAR(10) + CHAR(10) + N'Verifique a cadeia de conexão em CAPAS.exe.config.'),
    (N'msg_SolicitudDeVisitaConfirmada', N'Solicitud de visita confirmada.', N'Visit request confirmed.', N'Solicitação de visita confirmada.'),
    (N'msg_SuperariaSuLimiteDeHorasSemanalesConEsteTurnoElegiOtroEmplea', N'{0} superaría su límite de horas semanales con este turno. Elegí otro empleado.', N'{0} would exceed their weekly hour limit with this shift. Choose another employee.', N'{0} ultrapassaria o limite de horas semanais com este turno. Escolha outro funcionário.'),
    (N'msg_SuperariaSuLimiteDeHorasSemanalesElegiOtroEmpleado', N'{0} superaría su límite de horas semanales. Elegí otro empleado.', N'{0} would exceed their weekly hour limit. Choose another employee.', N'{0} ultrapassaria o limite de horas semanais. Escolha outro funcionário.'),
    (N'msg_TenesQueIndicarAlMenosUnaFranja', N'Tenés que indicar al menos una franja.', N'You must specify at least one time slot.', N'Você deve indicar pelo menos uma faixa.'),
    (N'msg_TodaviaQuedanFranjasSinAsignarNiMarcarComoDeficitDeCobertura', N'Todavía quedan franjas sin asignar ni marcar como déficit de cobertura.', N'There are still time slots not assigned or marked as a coverage shortfall.', N'Ainda há faixas sem atribuir nem marcar como déficit de cobertura.'),
    (N'msg_TraduccionesGuardadas', N'Traducciones guardadas.', N'Translations saved.', N'Traduções salvas.'),
    (N'msg_TurnoCanceladoConNotificados', N'Turno cancelado. Se notificó al administrador y a {0} empleado(s) disponible(s).', N'Shift cancelled. The administrator and {0} available employee(s) were notified.', N'Turno cancelado. O administrador e {0} funcionário(s) disponível(is) foram notificados.'),
    (N'msg_TurnoCanceladoSinNotificados', N'Turno cancelado. Se notificó al administrador (no se encontraron empleados disponibles para cubrirlo).', N'Shift cancelled. The administrator was notified (no available employees were found to cover it).', N'Turno cancelado. O administrador foi notificado (não foram encontrados funcionários disponíveis para cobri-lo).'),
    (N'msg_TurnoCubiertoYEmpleadoNotificado', N'Turno cubierto y empleado notificado.', N'Shift covered and employee notified.', N'Turno coberto e funcionário notificado.'),
    (N'msg_TurnoReasignadoYAmbosEmpleadosNotificados', N'Turno reasignado y ambos empleados notificados.', N'Shift reassigned and both employees notified.', N'Turno reatribuído e ambos os funcionários notificados.'),
    (N'msg_TurnoYaCubierto', N'Este turno ya fue cubierto por otra persona (o superarías tu límite de horas).' + CHAR(10) + N'Se actualizó la lista.', N'This shift was already covered by someone else (or you would exceed your hour limit).' + CHAR(10) + N'The list was updated.', N'Este turno já foi coberto por outra pessoa (ou você ultrapassaria seu limite de horas).' + CHAR(10) + N'A lista foi atualizada.'),
    (N'msg_UsuarioBloqueadoPorIntentosFallidosContactateConUnAdministra', N'Usuario bloqueado por intentos fallidos. Contactate con un administrador.', N'User locked due to failed attempts. Contact an administrator.', N'Usuário bloqueado por tentativas malsucedidas. Entre em contato com um administrador.'),
    (N'msg_UsuarioCreadoCorrectamente', N'Usuario creado correctamente.', N'User created successfully.', N'Usuário criado com sucesso.'),
    (N'msg_UsuarioDesbloqueado', N'Usuario desbloqueado.', N'User unlocked.', N'Usuário desbloqueado.'),
    (N'msg_UsuarioOContrasenaIncorrectos', N'Usuario o contraseña incorrectos.', N'Incorrect username or password.', N'Usuário ou senha incorretos.'),
    (N'msg_UsuarioSinHistorial', N'El usuario ''{0}'' no tiene historial de cambios registrado.' + CHAR(10) + CHAR(10) + N'No es posible restaurarlo desde historial. Use ''Recalcular y continuar''.', N'User ''{0}'' has no recorded change history.' + CHAR(10) + CHAR(10) + N'It cannot be restored from history. Use ''Recalculate and continue''.', N'O usuário ''{0}'' não tem histórico de alterações registrado.' + CHAR(10) + CHAR(10) + N'Não é possível restaurá-lo a partir do histórico. Use ''Recalcular e continuar''.'),
    (N'msg_VisitaAutorizada', N'Visita autorizada.', N'Visit authorized.', N'Visita autorizada.'),
    (N'msg_YaTenesUnIngresoRegistradoHoySinEgreso', N'Ya tenés un ingreso registrado hoy sin egreso.', N'You already have a clock-in today without a clock-out.', N'Você já tem uma entrada registrada hoje sem saída.'),
    (N'prefijo_Permiso', N'[Permiso] ', N'[Permission] ', N'[Permissão] '),
    (N'prefijo_Rol', N'[Rol] ', N'[Role] ', N'[Perfil] '),
    (N'tit_AccesoDenegado', N'Acceso denegado', N'Access denied', N'Acesso negado'),
    (N'tit_Atencion', N'Atención', N'Warning', N'Atenção'),
    (N'tit_Aviso', N'Aviso', N'Notice', N'Aviso'),
    (N'tit_Confirmar', N'Confirmar', N'Confirm', N'Confirmar'),
    (N'tit_ConfirmarCancelacion', N'Confirmar cancelación', N'Confirm cancellation', N'Confirmar cancelamento'),
    (N'tit_ConfirmarEliminacion', N'Confirmar eliminación', N'Confirm deletion', N'Confirmar exclusão'),
    (N'tit_ConfirmarRollback', N'Confirmar rollback', N'Confirm rollback', N'Confirmar rollback'),
    (N'tit_ContrasenaInvalida', N'Contraseña inválida', N'Invalid password', N'Senha inválida'),
    (N'tit_Error', N'Error', N'Error', N'Erro'),
    (N'tit_ErrorDelSistema', N'Error del sistema', N'System error', N'Erro do sistema'),
    (N'tit_Exito', N'Éxito', N'Success', N'Sucesso'),
    (N'tit_LimiteDeHorasSuperado', N'Límite de horas superado', N'Hour limit exceeded', N'Limite de horas excedido'),
    (N'tit_Listo', N'Listo', N'Done', N'Pronto'),
    (N'tit_LoginExitoso', N'Login exitoso', N'Login successful', N'Login bem-sucedido'),
    (N'tit_OperacionNoPermitida', N'Operación no permitida', N'Operation not allowed', N'Operação não permitida'),
    (N'tit_SinCobertura', N'Sin cobertura', N'No coverage', N'Sem cobertura'),
    (N'tit_SinHistorial', N'Sin historial', N'No history', N'Sem histórico'),
    (N'tit_SinUmbralConfigurado', N'Sin umbral configurado', N'No threshold configured', N'Sem limite configurado'),
    (N'tit_YaNoDisponible', N'Ya no disponible', N'No longer available', N'Não está mais disponível');

IF NOT EXISTS (SELECT 1 FROM IDIOMA WHERE NOMBRE LIKE 'Ingl%' OR NOMBRE = 'English')
    INSERT INTO IDIOMA (NOMBRE, HABILITADO, PREDETERMINADO) VALUES ('Inglés', 1, 0);
IF NOT EXISTS (SELECT 1 FROM IDIOMA WHERE NOMBRE LIKE 'Portugu%')
    INSERT INTO IDIOMA (NOMBRE, HABILITADO, PREDETERMINADO) VALUES ('Portugues', 1, 0);

DECLARE @esId  INT = COALESCE((SELECT TOP 1 ID FROM IDIOMA WHERE PREDETERMINADO = 1 ORDER BY ID),
                              (SELECT TOP 1 ID FROM IDIOMA WHERE NOMBRE LIKE 'Espa%' ORDER BY ID));
DECLARE @ingId INT = (SELECT TOP 1 ID FROM IDIOMA WHERE NOMBRE LIKE 'Ingl%' OR NOMBRE = 'English' ORDER BY ID);
DECLARE @ptId  INT = (SELECT TOP 1 ID FROM IDIOMA WHERE NOMBRE LIKE 'Portugu%' ORDER BY ID);

DECLARE @porIdioma TABLE (IDIOMA_ID INT, CLAVE VARCHAR(100), TEXTO NVARCHAR(400));
INSERT INTO @porIdioma SELECT @esId,  CLAVE, ES FROM @textos WHERE @esId  IS NOT NULL;
INSERT INTO @porIdioma SELECT @ingId, CLAVE, EN FROM @textos WHERE @ingId IS NOT NULL;
INSERT INTO @porIdioma SELECT @ptId,  CLAVE, PT FROM @textos WHERE @ptId  IS NOT NULL;

BEGIN TRANSACTION;

DELETE tr FROM TRADUCCION tr
JOIN CONTROL_IDIOMA c ON c.ID = tr.CONTROL_ID
WHERE NOT EXISTS (SELECT 1 FROM @textos t WHERE t.CLAVE = c.CLAVE);

DELETE c FROM CONTROL_IDIOMA c
WHERE NOT EXISTS (SELECT 1 FROM @textos t WHERE t.CLAVE = c.CLAVE);

UPDATE c SET TEXTO_DEFAULT = t.ES
FROM CONTROL_IDIOMA c JOIN @textos t ON t.CLAVE = c.CLAVE;

INSERT INTO CONTROL_IDIOMA (CLAVE, TEXTO_DEFAULT)
SELECT t.CLAVE, t.ES FROM @textos t
WHERE NOT EXISTS (SELECT 1 FROM CONTROL_IDIOMA c WHERE c.CLAVE = t.CLAVE);

UPDATE tr SET TEXTO = pi.TEXTO
FROM TRADUCCION tr
JOIN CONTROL_IDIOMA c ON c.ID = tr.CONTROL_ID
JOIN @porIdioma pi ON pi.CLAVE = c.CLAVE AND pi.IDIOMA_ID = tr.IDIOMA_ID;

INSERT INTO TRADUCCION (IDIOMA_ID, CONTROL_ID, TEXTO)
SELECT pi.IDIOMA_ID, c.ID, pi.TEXTO
FROM @porIdioma pi
JOIN CONTROL_IDIOMA c ON c.CLAVE = pi.CLAVE
WHERE NOT EXISTS (SELECT 1 FROM TRADUCCION tr WHERE tr.IDIOMA_ID = pi.IDIOMA_ID AND tr.CONTROL_ID = c.ID);

COMMIT TRANSACTION;

SELECT i.NOMBRE AS IDIOMA, COUNT(tr.CONTROL_ID) AS TRADUCCIONES
FROM IDIOMA i LEFT JOIN TRADUCCION tr ON tr.IDIOMA_ID = i.ID
GROUP BY i.NOMBRE;
GO
